### ISSUE TITLE
Add Solarized themes as editor themes

### ISSUE THREAD

**Issue by OscarGodson** [OscarGodson/EpicEditor#1]
http://ethanschoonover.com/solarized

Eventually it'd be nice to have these color themes, but it's not too important.

**Comment by dadambickford** [comment]
https://github.com/ccampbell/rainbow
just saw this on the front page of GH today, sounds cool.

**Comment by OscarGodson** [comment]
I'm just gonna close this. No one has requested this theme and I also don't want a bunch of themes in the default build of EpicEditor.
