### ISSUE TITLE
Editor state bug when exiting full screen mode

### ISSUE THREAD

**Issue by sebnitu** [OscarGodson/EpicEditor#117]
I noticed that when I enter full screen mode, then exit, the editor get's the `epiceditor-preview-mode` class even when I'm still in edit mode.

Screenshot: http://cl.ly/GpxA

![http://f.cl.ly/items/3n470R28383o1s0C2F3v/Screen%20shot%202012-05-22%20at%207.12.46%20PM.jpg](http://f.cl.ly/items/3n470R28383o1s0C2F3v/Screen%20shot%202012-05-22%20at%207.12.46%20PM.jpg)

**Comment by OscarGodson** [comment]
@dadambickford can you take care of this one ASAP?

**Comment by OscarGodson** [comment]
This is important because it affects the button states and then the buttons look broken and stuff. Should be simple just on the exit fullscreen function change the class based on the state.
