### ISSUE TITLE
"Sticky" shortcuts

### ISSUE THREAD

**Issue by OscarGodson** [OscarGodson/EpicEditor#127]
I can't reproduce this reliably but the best way to reproduce this, I guess, is to just write a document. Switch tabs, copy random bits, paste them, write, etc. Try to break it. At some point, sometimes, the shortcut keys get sticky. The "modifier" key seems to always return true therefore pressing a shortcut key like `f` will trigger fullscreen or `o` will just not show up in the editor (because it's triggering the `edit()` method).

**Comment by larzconwell** [comment]
Oh just to let you know, F key gets stuck as well. When you press it, it toggles full screen.

**Comment by OscarGodson** [comment]
Yeah. All shortcuts should "stick" when this happens. Not sure why yet, but altKey always returns true sometimes. Hmm

**Comment by dadambickford** [comment]
Can't reproduce here in chrome or FF, I remember it happening once or twice a while back, but it never happened repeatedly.

**Comment by OscarGodson** [comment]
@dadambickford Can you try https://t.co/7oLbp7NR (written up by @larzconwell)? I believe he's on Ubuntu like you. Those steps don't work for me personally. Also, can you see #133 who is a user on W7?

**Comment by OscarGodson** [comment]
I could only come up with a half ass fix. I'm setting `isMod` (what checks if the modifier key is being pressed) to `false` after each successful key shortcut that is executed. The only problem is you can't do back to back shortcuts like: `alt+p o` to preview then flip back to edit without lifting `alt`. I think for the most part this is ok, but I'll wanna come up with some other fix eventually (if possible).

@larzconwell I could only reproduce what you mentioned on Win7 Firefox. Could you see if the fix which is now in develop also works for your OS and browser? (fingers crossed)

**Comment by dadambickford** [comment]
i was still unable to purposely produce any sticky shortcuts with the steps provided. ctrl+alt+arrows just changes desktops for me, and doesn't have any effect messing with epic editors shortcuts.

**Comment by OscarGodson** [comment]
@dadambickford So after switching tabs and going back the shortcuts were still working?

**Comment by dadambickford** [comment]
like a charm, switching tabs in the browser, switching the desktop tabs with the short cuts, minimizing, maximizing, i couldn't get them to fail.

my only experience with it was like i said earlier, it happened once or twice months ago and i couldn't reproduce then either, so no clue what caused it.

**Comment by OscarGodson** [comment]
Nice, alright, well in that case ill wait for @larzconwell to reopen the issue if it persists after this change. Thanks @dadambickford

**Comment by larzconwell** [comment]
I am in fact running Ubuntu and my ctrl+alt+arrows switch desktops as well. 

It mostly fixed it, the _only_ time it messes up now is when I change desktops then try to use the S key. the O key is working perfectly in all cases.

**Comment by OscarGodson** [comment]
I think I know the problem. DMed you on Twitter, but thought I should write here so it's saved. Since I can't reproduce it I want to make sure what I think will fix it actually fixes it before pushing to develop. I think adding the highlighted line to `src/editor.js` would fix it:

![](https://img.skitch.com/20120627-jru6csrsan345exg3qpmsqg8rq.png)

**Comment by larzconwell** [comment]
Yep that works perfectly!

**Comment by OscarGodson** [comment]
Awesome ill push a fix right now then. Thanks for the help!

**Comment by larzconwell** [comment]
Your welcome!
