### ISSUE TITLE
[Code inside] Add setContent(content) function

### ISSUE THREAD

**Issue by Elv13** [OscarGodson/EpicEditor#128]
I probably missed something reading the doc, I have not found how you are supposed to get and set MD content. If it is really not possible, then please add those 2 functions:

``` javascript
   EpicEditor.prototype.setContent = function(cont){
      this.editor.value = cont;
      this.previewer.innerHTML = this.exportHTML();
      this.emit('content');
   }

  EpicEditor.prototype.exportMD = function(){
      return this.editor.value;
  }
```

They are usefull to load and save content using AJAX

**Comment by johnmdonahue** [comment]
I like this idea. We're getting close to the beta release that might actually address this. @Elv13 would you mind checking out the beta API to see if this will work for what you're trying to do: https://github.com/OscarGodson/EpicEditor/tree/0.1.0-build-refactor#importfilefilenamecontent

**Comment by OscarGodson** [comment]
It's done. I made some text changes, i'll try to get it finished tonight, soft launch and make an announcement on Monday.

As for what you mention, yeah, `exportFile` in the 0.1.0 release does what you mention (it allows you to export raw content by default and HTML by passing it a parameter). And in the old API, `import()` seems to do basically `setContent`, no?

**Comment by OscarGodson** [comment]
@Elv13 I merged in the beta release. I'm gonna close this for now, but comment/open it again if `exportFile` and `importFile` don't do what you want :)
