### ISSUE TITLE
container options not working

### ISSUE THREAD

**Issue by romme86** [OscarGodson/EpicEditor#138]
i discovered an issue that i hope is only my fault:

When i change the container option both in the min.js file or setting the var option. the editor stops working.
it does not load.

I did that because i wanted to run multiple editor instances in one page and use them separately, i don't know if there is another better way.

**Comment by OscarGodson** [comment]
Could I see your code? Not sure what you mean by "setting the var option"? You can load as many instances as you want. Our test suite runs over 70 editors at once :)

This should work:

``` javascript
editor1 = new EpicEditor({ container: 'editor1' }).load();
editor2 = new EpicEditor({ container: 'editor2' }).load();
```

Example here: http://jsbin.com/obezop/edit#javascript,html

**Comment by romme86** [comment]
ok i'll try this way of passing options.
i did this:

<script>
  var opt { ... container='editor1' ...}
  editor1 = new EpicEditor(opt).load.
</script>

**Comment by OscarGodson** [comment]
That should work fine as long as you have 2 different option objects. You can't have two elements with the same ID in HTML.

**Comment by OscarGodson** [comment]
I'm going to close this for now, but feel free to reopen it or comment again if this didn't answer your question.
