### ISSUE TITLE
How do you set the width of the editor?

### ISSUE THREAD

**Issue by bingomanatee** [OscarGodson/EpicEditor#143]
Basic question; where / how is the width of the editor set?

**Comment by OscarGodson** [comment]
It's automatic. The editor is placed in whatever container you give it.

**Comment by johnmdonahue** [comment]
To add to that: if you explicitly set a width on the container it will use that, otherwise it will be as wide as any parent allows.

**Comment by OscarGodson** [comment]
Yes, so, in your CSS you could do:

``` css
#editor {
  width: 400px;
}
```

Check out the CSS on http://epiceditor.com

**Comment by OscarGodson** [comment]
Closing for now. Reopen if we didn't answer your question or something isn't working :)
