### ISSUE TITLE
Ability to inject text after EpicEditor is loaded

### ISSUE THREAD

**Issue by ericlbarnes** [OscarGodson/EpicEditor#145]
Maybe this feature already exists and I missed it. What I would love is the ability to dynamically add text into the editor after it is initialized. For instance I want to use mousetrap.js http://craig.is/killing/mice so we can have shortcuts for various things.

**Comment by ericlbarnes** [comment]
doh - `editor.getElement('editor').body.innerHTML += "My appended text";`

**Comment by OscarGodson** [comment]
@ericbarnes Yes, thats one way of doing it, but kinda kludgy :) There's an option if you want the same text in all new editors:

``` js
var editor = new EpicEditor({ file: defaultContent: 'Hello World' });
```

And if you add stuff dynamically:

``` js
editor.importFile('foo', '#hello\nworld')
```

**Comment by OscarGodson** [comment]
Curious what your project is too. What are you doing with the editor and mousetrap together?

**Comment by ericlbarnes** [comment]
Thanks for the follow up and I agree that is much nicer.  Currently building a support type app where people can have a saved list of responses. So when they are typing a response they can type something like ;forgotpass and it auto completes into "Sorry you are having issues with your password. Please follow these steps.... "

**Comment by OscarGodson** [comment]
Very cool. Yeah, `importFile` should work for you fine then. Also, unlike your method above, this will trigger all the CRUD events too if you ever need them. Send me a demo when it's ready ;)
