### ISSUE TITLE
Split mode normal screen ( Add fullscreen APIs )

### ISSUE THREAD

**Issue by bootstraponline** [OscarGodson/EpicEditor#146]
Is it possible to have a split mode without forcing the user to enter full screen?

**Comment by OscarGodson** [comment]
You mean like native fullscreen in Chrome? Not with an option, but I'll add it. Maybe a boolean `useNativeFullscreen`. I'll add it to the 0.1.2 release. 

For now tho you can do it manually in the source pretty easily. I think you can just change this line (401): https://github.com/OscarGodson/EpicEditor/blob/68997cba2bbaaf4c8b4ac44bfe03966ecee33d97/epiceditor/js/epiceditor.js#L401

to be `false`.

**Comment by bootstraponline** [comment]
I mean [something like this](http://bootstraponline.github.com/livepreview/public/). It's split screen, however I didn't have to press F11 to enter "full screen mode." It would replace the "switch to preview mode" because it would be split screen for previewing, without requiring full screen. It'd be nice to have as an option.

**Comment by OscarGodson** [comment]
No, again, but it'd be super easy to add. I'll add an API call to enter fullscreen as well as being able to turn off native fullscreen so that you could do like:

``` js
var editor = new EpicEditor({ useNativeFullscreen: false });
editor.load(function () {
  editor.fullscreen();
});
```

And it'd look like your example. I'll try to get both of these in.

**Comment by bootstraponline** [comment]
That'd be great!

**Comment by OscarGodson** [comment]
@bootstraponline quick question, would you rather have `fullscreen()` toggle opening and closing fullscreen (like it does internally) or would you rather have an explicit `exitFullscreen()`?

**Comment by bootstraponline** [comment]
I'd prefer `exitFullscreen()` so that it's a no-op if the editor is not already in full screen mode.

**Comment by OscarGodson** [comment]
@bootstraponline Alright, pull develop! I've added the fullscreen API stuff. There's 2 new methods enterFullscreen and exitFullscreen as well as 2 new events fullscreenenter and fullscreenexit and an option to useNativeFullscreen so you can turn off native fullscreen if you want.

Let me know if this is what you expected and is working well!

**Comment by OscarGodson** [comment]
Also I did an example for you :) http://jsbin.com/aketom (http://jsbin.com/aketom/edit)

Less code than originally expected, now just:

``` js
var editor = new EpicEditor();

editor.load(function () {
  editor.enterFullscreen();
});
```

**Comment by bootstraponline** [comment]
Wow! That's perfect.

**Comment by OscarGodson** [comment]
Glad to hear that!
