### ISSUE TITLE
Add a short tutorial on how to write a custom parser

### ISSUE THREAD

**Issue by Le-zz-ge-zz-n-zz-d** [OscarGodson/EpicEditor#149]
I am very interested in looking at how to efficiently write a parser. It would really be beneficial to have a short tutorial on how to write a small custom parser rather than a demonstration using Showdown or Marked.

**Comment by OscarGodson** [comment]
It really depends on what the parser is parsing on how to make it efficient. I personally haven't ever written a real parser, so I might not be the best person to ask :)

Or, do you mean strictly for EpicEditor? In that case you just write whatever you want and have it return a string. This would, "technically" be the most effcient parser:

``` js
EpicEditor({
  parser: function (str) {
    return str;
  }
});
```

**Comment by Le-zz-ge-zz-n-zz-d** [comment]
@OscardGordan: I see. Thank you for the response :) I was just wondering if there were any special requirements because of the following: In the full-screen mode, when you show live-previews to the right, I am assuming that it sends the entire text to the parser (or please correct me if I am wrong and skip the rest of this post). 

So I was just curious if EpicEditor does anything fancy here. For instance, pass only the last two or three newly written lines to the parser? Of course, this is assuming that parsing the entire text every time to render a live preview would consume significant resources.

PS: I will dig into the source code tonight after work. :)

**Comment by OscarGodson** [comment]
Currently It just sends the entire thing to the parser. To save on performance it only does this after you pause typing for `250`. We haven't gotten that far into that granular of optimization, but hope to someday. :)

**Comment by Le-zz-ge-zz-n-zz-d** [comment]
@OscarGodson Fair enough. I'm currently working on using this on larger text chunks. I'll see if there is a big performance hit and think about further solutions otherwise whatever is done will end up as pre-mature optimization. Thank you for your time.
