### ISSUE TITLE
Support key shortcuts

### ISSUE THREAD

**Issue by OscarGodson** [OscarGodson/EpicEditor#15]
Key commands should allow for preview and edit modes.

Also, the key commands should only work if the editor is in focus.

**Comment by OscarGodson** [comment]
Currently in the shortcuts branch we support <kbd>alt+e</kbd> for edit, <kbd>alt+p</kbd> for preview, and <kbd>alt+f</kbd> for fullscreen. There's a bug in Firefox (not us) where <kbd>alt+e</kbd> will not fire on FF for Mac. I reported it to them here: https://bugzilla.mozilla.org/show_bug.cgi?id=731941

Will merge into master and gh-pages after @dadambickford checks in IE9

**Comment by dadambickford** [comment]
<kbd>alt+e</kbd> fires in IE9, but the `requestValue = false` which is supposed to act like `preventDefault()`, is not blocking the native <kbd>alt+e</kbd> action, which drops down the "Edit" menu.

**Comment by OscarGodson** [comment]
We should also allow devs to override the shortcuts with their own. Maybe like:

``` javascript
ee.options({
  shortcuts:{
    modifier:18 //alt
  , edit: 81 //q
  }
}).load();
```

We'd need to slightly change how we check for alt press by using `var isAlt` again and remove the `e.altKey` code (don't need both and if we want it customizable then we cant use `e.altKey`)
