### ISSUE TITLE
Some help with editor content flow

### ISSUE THREAD

**Issue by bingomanatee** [OscarGodson/EpicEditor#153]
I would like to estalish the following work flow:

1: use epic editor to create marked-up content.
2: save the smallest possible version of the code (sent to Node.js via Ajax, saved in a textfield in mongo)
3: present the formatted content on a new page. (prob. format it on server side w/node.js). 

What is the best way to format the streamlined content and what is the best way to export from your editor, with the smallest possible file size?

Thanks

Dave

**Comment by OscarGodson** [comment]
You can export the raw editor content with just `exportFile()`. What do you mean "format the streamlined content" exactly? You can't really change the content much since whitespace matters for line breaks and stuff, but `exportFile()` should give you what I think you want :) Does that help?

**Comment by OscarGodson** [comment]
closing this for now since there hasn't been a reply. Feel free to reopen if the above didn't help.
