### ISSUE TITLE
Preview state is not being retained on unload & load

### ISSUE THREAD

**Issue by sebnitu** [OscarGodson/EpicEditor#161]
Sorry, I know I'm making a lot of these :P

Just noticed that when the Editor is loaded it doesn't keep it's previous state (preview mode) and just defaults to edit mode. Is this intended?

**Comment by OscarGodson** [comment]
That'd be a bug. That's something that I just overlooked. I set it to go to edit mode on load, but it should actually check if a state exists, and if a state exists use that otherwise default to edit. I'll get this into the 0.1.2 release also.

**Comment by OscarGodson** [comment]
@sebnitu Can you pull and try now? The change was pretty simple, but I did some cleanup. All tests pass still tho.

If you're interested:  
I was setting the state at the top to edit on each load. Now I check if edit and preview state is false and if they're both false (first load) then I set it to edit. I also cleaned up how I was setting it to edit/preview. Before I was just display none-ing the preview iframe on load, now I'm actually calling the API methods to preview and edit.

**Comment by sebnitu** [comment]
Awesome, works like a charm :D

**Comment by OscarGodson** [comment]
Nice! Keep the bug reports coming :)
