### ISSUE TITLE
Firefox will auto add line break

### ISSUE THREAD

**Issue by vicalloy** [OscarGodson/EpicEditor#171]
my text is

```
a
b
c
```

and exportFile() get

```
a

b

c
```

**Comment by OscarGodson** [comment]
What version are you on? I'm not seeing that at all. Are you using export to export the raw text or as HTML?

![](https://img.skitch.com/20120817-cab181jrqhedd86p5uqnx52ydi.png)

**Comment by vicalloy** [comment]
Firefox 13.0.1
- cfg = {"autoSave": False, 'clientSideStorage': False}
- add text and use exportFile() to save it to db.

```
a
b
c
```
- get text from db and use defaultContent to load it.  I can see a blank after every line(a \n?).

```
# in EpicEditor
a[blank]
b[blank]
c[blank]
```

```
#exportFile()
a

b

c
```

may some bug in "defaultContent"?

**Comment by OscarGodson** [comment]
Can I see all your code? Also, not sure if it's part of the problem, but `False` doesn't exist in JS for booleans, you need `false`. `False` will error out (unless you're doing something weird like `False = false`).

Also, `defaultContent` literally just takes what you give it and saves it to the client side storage you specified (in your case a plain object):

``` javascript
 _defaultFile.content = self.settings.file.defaultContent;
```

If I recreate what you give me using localStorage as the "db" I don't see this here: http://jsbin.com/owirij/9/edit. Maybe it's what your DB is giving back or how you're saving it to your DB? Can you reproduce this on JSBin without your DB? I also saw this on StackOverflow: http://stackoverflow.com/questions/11512592/ruby-markdown-string-processing-issue-with-encoding which suggests that you need to do some string encoding on the backend in some cases.

**Comment by OscarGodson** [comment]
wait you're seeing, literally, `[blank]` or a space?

**Comment by vicalloy** [comment]
"False" is my python code.
It may cause by "\r\n"

``` .js
  file: {
    defaultContent:localStorage['db'] || 
    "aa\r\nbb\r\nddd"
  }
```

**Comment by OscarGodson** [comment]
Yes, that might do it, but how do you reproduce that? When I press enter it only gives me an `\r`?

**Comment by vicalloy** [comment]
"id_body" is a textarea.
I export it to a textarea and save it to server.

``` .js
var bdEditor = new EpicEditor({"file": {"defaultContent": "\r\na\r\n b\r\n  c\r\n", "name": "body"}, "basePath": "http://vicalloy.sinaapp.com/dpress/dpress/epiceditor", "container": "epic_body_id", "clientSideStorage": false, "autoSave": false}).load(); 
$('#post_form').submit(function(){
    $('#id_body').val(bdEditor.exportFile());
});
```

**Comment by OscarGodson** [comment]
Even if I write it to a textarea then save it from the textarea's value I'm not seeing `\r\n`s: http://jsbin.com/owirij/11/edit

The `defaultContent` you have above is dynamically getting put there by your Python code, right? Using localStorage and JSBin, can you reproduce this problem to make sure it has nothing to do with your Python code or how the database/form is transmitting the text?

**Comment by vicalloy** [comment]
"\r\n" is auto added by my python web framework.
I removed "\r" before set to defaultContent.
It work now.

**Comment by OscarGodson** [comment]
Great :) glad we got it worked out and it wasn't a EpicEditor bug!
