### ISSUE TITLE
Concept for Plugins: contextual plugins

### ISSUE THREAD

**Issue by fuddl** [OscarGodson/EpicEditor#177]
other wysiwyg editors have this thing called plugins: buttons that can be clicked to format text. Clients want them. At least they need it in order to learn markdown.

But, what we don't want:

![NO](http://fissl.com/zeug/shit.png)

Because we are cool and minimal. We don't need to see _all_ these plugins if we don't need them. So I thought about plugins that appear if the author _might_ use them. For example **by selecting text**. 

**By default we don't see any plugin.**
## Inline elements

For example if you select **a single word within a block**, epicedit offers you to wrap in in inline elements:
![inline elements](http://fissl.com/zeug/contextuial-plugins-inline.png)

so now you can chose to wrap the selected text to be a link, strong, empathised or a quote.

After clicking(or selecting somehow it by keyboard) the text will be marked as link:
![link](http://fissl.com/zeug/contextuial-plugins-inline-link.png)

Or after clicking empathise:
![em](http://fissl.com/zeug/contextuial-plugins-inline-em.png)
## Block elements

If you select **a whole line** it offers you to format it as a block object:

![line](http://fissl.com/zeug/contextuial-plugins-block.png)

Such as a list item, an ordered list item, a headline or a blockquote.

It only offers you a headline level 1 because other levels make no sense here. 
## Headlines

until you have a <code>h1</code> above you selection. Then it offers you a deeper level:

![headline level 2](http://fissl.com/zeug/contextuial-plugins-block-2.png)

Also headline are only suggested as long as you select a **single line block object** because multi line headlines do not work in markdown.

It would also be nice to use these plugins in preview mode, but that's another issue maybe.

Well, what do you think?

**Comment by OscarGodson** [comment]
I like this a lot and it's been something I've wanted to add to the editor for a long time (5 months ago was the original post: #41). 90% of this will be possible to do very soon thanks to @hongymagic 's pull request #166. 

I was thinking something like this actually: #113

However, I do like this and here's some of my thoughts
1. What if you know you want a link or bold text? With this spec you'd have to type it, stop, highlight, select, then start typing again. 
2. Technically it's semantically right to have an h1, h2, etc, but you might not want that and for legitimate reasons. For example, lets say you replaced a WYSIWYG with this editor, and the title of the post is an input field above the WYSIWYG (like most CMSs, i believe), you wouldn't want an `<h1>`, you'd just want an `<h2>` and below. Or, many sites have the title of the site as their h1, titles of their posts at h2s, and now you'd want 3 and below. So, you'd still always need to be able to select all 6 header tags.
3. Multi line headlines work fine. You might want to write out your headlines before you fill it in then select them all and make them headlines. This works fine:

``` md
## An Embeddable JavaScript Markdown Editor
## hello
```

Produces: 

## An Embeddable JavaScript Markdown Editor

## hello

But I like your approach so far. The biggest problem with WYSIWYG buttons currently is that we allow any parser. right now you can drop in a wiki parser and it'll just work. With buttons I don't yet know how the API will be to support the buttons. We might actually end up making this a sort of extension to the editor.

**Comment by fuddl** [comment]
1. Yes I have no Idea yet to make that easier. Or what do you mean?
2. Nothing hinders you to write the h3 headline manually but my approach only tries to _suggest_ what is logical. If the user starts the document with h3 it should suggest h3, h4, h5 and h6. I think the main purpose of this is showing the user how markdown works. As soon as he understands, he won't use the buttons any more ;). And yes, the headline starting level should be configurable.
3. Oh, that are two headlines. Not one multi line headline :)

**Comment by OscarGodson** [comment]
1. Well, if the buttons were always there for example, clicking the bold text button would create `**|**` where `|` is the cursor.
2. Some people just really like clicking buttons to style things. If you sit with someone who's really not tech savvy you'll see this. They'll type some stuff. Stop. Click the bold button. Start typing again and yeah. They're pretty tedious. The people who need to button in the first place would rather click it. Also, they'll actually never learn if they're not supposed to type an h1 and in the first place. They'll click h1, notice it looks terrible on their site because they needed an h3 and then never click the button again.
3. Yes, but you'd still wanna mark a bunch of lines as something. Also, selecting a single line to make italic, or bold, etc wouldn't work. Also, trying to figure out if it's a single word, one line, or a block would be incredibly hard. If you can show a JSBin link of that tho, it'd help.
