### ISSUE TITLE
Path to EpicEditor CSS

### ISSUE THREAD

**Issue by jcswart** [OscarGodson/EpicEditor#182]
Are there known issues with using EpicEditor and Twitter Bootstrap?  Both make use of the class name "container".  My issue stems from the fact that my editor pane does not have any theme, I can type text but I cannot 'see' anything.

When I view the source to see where the EpicEditor iframe's are pulling their CSS and they are not using the proper path.  If I try to manually edit this by setting the options when i load EpicEditor it still does not get the path to the css correct.

Can anyone offer assistance on this matter?

**Comment by OscarGodson** [comment]
There should be no conflicts with bootstrap as its all contained in an iframe. Whats your directory structure look like? As in, where are EEs assets?

**Comment by jcswart** [comment]
Thanks for the reply.  I am using Laravel a PHP framework. 
- Project Root
  - Application
    - Views
      - Admin
        - editor.php (contains my epic editor code, the div where the editor should be viewed)
  - Public
    - epiceditor (all of epiceditors .js and .css files)

**Comment by jcswart** [comment]
The iframes css links to 'http://localhost:8888/projectroot/admin/edit_post/epiceditor/themes/editor/epic-dark.css'  It is using the current path as the base.  The page's URL in question is http://localhost:8888/projectroot/admin/edit_post/1.  That is where I have my epiceditor.  

The css link above SHOULD be http://localhost:8888/projectroot/epiceditor/themes/editor/epic-dark.css, that is where the files are.  Yet it is using using the current page as the base, and creating the url relative to that.  

How to I set: http://localhost:8888/projectroot/epiceditor/themes/editor/epic-dark.css as the proper location?

If I add

> (function(){
>             var opts = {
>                 themes: {
>                     base: 'http://localhost:8888/tcdrinker/epiceditor/themes/editor/epic-dark.css'
>                 }
>             }
>             var editor = new EpicEditor(opts).load();

Adding this code does not change the link in the iframe.

**Comment by OscarGodson** [comment]
Awh ok that makes sense. Youll want to set the `basePath` option to `basePath: '/epiceditor'` in this case.

**Comment by jcswart** [comment]
Thank you very much Oscar this fixed my problem!  I really appreciate the quick response!

**Comment by OscarGodson** [comment]
:thumbsup:
