### ISSUE TITLE
Full screen edit mode does not work with Chrome & Firefox

### ISSUE THREAD

**Issue by davidshen84** [OscarGodson/EpicEditor#186]
My OS is _64bit_, and my Chrome & Firefox are updated to _latest_. When I enter the full-screen edit mode, Chrome/Firefox would consume very high CPU utilization, and I cannot actually type in the editor.

**Comment by OscarGodson** [comment]
I don't think 32 or 64 bit makes a difference, but OS might.

Could you open Chromes processes window and take a screenshot of it and then open full screen and take one again so I can see what the increase is? Also can you reproduce this on epiceditor.com? Haven't you been using EE awhile? I haven't updated master in quite a long time. Hmm...

**Comment by davidshen84** [comment]
Thank you. I found this issue does not exist on epiceditor.com. I think it
is my problem :) Please close this bug.

On Tue, Oct 23, 2012 at 12:15 PM, Oscar Godson notifications@github.comwrote:

> I don't think 32 or 64 bit makes a difference, but OS might.
> 
> Could you open Chromes processes window and take a screenshot of it and
> then open full screen and take one again so I can see what the increase is?
> Also can you reproduce this on epiceditor.com? Haven't you been using EE
> awhile? I haven't updated master in quite a long time. Hmm...
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/OscarGodson/EpicEditor/issues/186#issuecomment-9690185.

## 

Regards，
David Shen

http://about.me/davidshen
https://twitter.com/#!/davidshen84
