### ISSUE TITLE
themes shouldn't have to be inside the epiceditor directory

### ISSUE THREAD

**Issue by themightychris** [OscarGodson/EpicEditor#196]
I want to avoid modifying modifying the epiceditor source tree when linking in new preview themes. Please update the config option handling so that theme CSS paths matching /^https?:\/\//i don't get prefixed with basePath and then users can link to external CSS files

**Comment by OscarGodson** [comment]
Kinda "magical" since basePath implies it's the base path to everything, but I think it makes sense because you'd never have http://foo.com/my/themes/http://...

**Comment by OscarGodson** [comment]
This has landed in develop with tests. Thanks!
