### ISSUE TITLE
Marked v0.2.7 is available

### ISSUE THREAD

**Issue by chjj** [OscarGodson/EpicEditor#197]
@OscarGodson,

Marked 0.2.7 which adds a few more gfm features (gfm tables, gfm strikethrough, gfm line breaks) is now available. Just thought I'd let you know.

**Comment by OscarGodson** [comment]
Awesome thanks! These are excellent. Ill put this in right away,

**Comment by OscarGodson** [comment]
annnnnd done. The tables look great and I had styled them ahead of time for whenever you got around to this! 
![Screen Shot 2013-01-08 at 1 17 34 AM](https://f.cloud.github.com/assets/20615/49670/46888e1e-5974-11e2-9ea2-7937d28da64b.png)
