### ISSUE TITLE
a problem of code block indent , or a bug?

### ISSUE THREAD

**Issue by shatle** [OscarGodson/EpicEditor#201]
i create a new epiceditor and load content from importFile method, but the result is not right!

Ex:

```
window.er=new EpicEditor().load()
window.er.importFile('test', '`code`\n\n    code block')
console.log window.er.editor.innerText 
```

The output is "`code`\n\n  code block", 4 indents become to 2 , why?

**Comment by OscarGodson** [comment]
It's working fine for me. Go to http://epiceditor.com and do:

```
editor.importFile('test', '`code`\n\n    code block')
```

![Screen Shot 2013-01-16 at 8 03 45 AM](https://f.cloud.github.com/assets/20615/71766/762dc502-5ff6-11e2-99ae-319aea252680.png)

(I put something with 2 spaces so you can see that the import is still 4)

However, I might be on a different setup. What's your browser, browser version and EpicEditor version?

Also, not sure if this matters, but:

```
console.log window.er.editor.innerText 
```

That should just error out without the `(` and `)` and `window.er.editor.innerText` shouldnt work either. That should always be undefined in your case. If you want the editor's content you need to use `exportFile`

**Comment by shatle** [comment]
Thanks, I test in  http://epiceditor.com and success, as your work! but my app still has this problem.
Then i ref http://epiceditor.com/epiceditor/js/epiceditor.js in my app,  not work. 
Misted!
The same env, u work, but i am not!

---

```
console.log window.er.editor.innerText
```

I use coffeescript!

---

Thanks again! if i find the reason, i will write it in here.

**Comment by OscarGodson** [comment]
Huh, well good luck! Let me know if you need more help.

**Comment by shatle** [comment]
Maybe
- The epiceditor tag is unabled to be hide
- Does not have other iframes

**Comment by OscarGodson** [comment]
Not sure I follow. EpicEditor tag? Does not have other iframes?
