### ISSUE TITLE
Minified 0.2.0 EpicEditor, UTF8, and breaking spaces

### ISSUE THREAD

**Issue by brentjanderson** [OscarGodson/EpicEditor#205]
When using `.import` or `file.defaultContent` to set up a document for editing, EpicEditor was throwing in the UTF8 sequence for a nonbreaking space but outputting it as ASCII (`Â`), making my text both ugly and incorrect. Saving back didn't cause any issues (presumably a parser in the middle converted the sequence back into real unicode), but editing was a pain because every space was replaced with `Â`.

After playing with my own server-side encodings, database collations, and other possible issues, I switched from minified EpicEditor to the raw EpicEditor for a deeper debugging of EpicEditor itself. This solved the problem - simply using the non-minified version of EpicEditor eliminated the issue. 

I've isolated the issue down to UglifyJS mangling line 171 of editor.js. `replace(/ /g, '\u00a0');` becomes `.replace(/ /g, " ");`.

A quick fix is to find line 4, chars 1477-1480 (`" "`) in epiceditor.min.js and replace them with `'\u00a0'`.

After experimenting with UglifyJS and the build tools, I couldn't find a way to make sure this fix becomes an automated part of the build process, but I thought I'd report this here to raise awareness and just in case someone else finds EpicEditor unusable for the same reason.

**Comment by OscarGodson** [comment]
Hmm, I believe you, but I can't reproduce it on my end. I checked out master (0.2.0) and used the .min version then ran this in Chrome and Firefox:

``` js
editor.importFile('test', 'a          b');
var str = editor.exportFile('test');
var i = 0;
for (i = 0; i < str.length; i++) {
  console.log(str.charCodeAt(i));
}
```

And it returned:

```
97
32 (x10)
98
```

Which is correct. I believe the `\u00a0` will return `160` and there would be like 5 `160`s and 5 `32`s. (real space and then nbsp). 

Could you give me a way to reproduce it and to somehow track what characters? I need a way to repro it so I can hotfix it. I also want to then setup automated tests on the minified version and write a test to catch this in the future and then, lastly, report it to Uglify.

**Comment by brentjanderson** [comment]
I forgot to include one important detail: The string I am using for my importFile is coming from a hidden input field whose contents I fetch via JQuery `$('input[type="hidden"]).val()`. That may make a difference. Below is the entire javascript file I use. Note that while I use the `file.defaultContent` option here, I had the exact same results using the `.importFile` function.

``` javascript
var content = $('input[type="hidden"]').val();

var opts={
    basePath:"",
    clientSideStorage:false,
    theme:{
        base:"/css/editor/base.css",
        preview:"/css/editor/preview-bartik.css",
        editor:"/css/editor/editor-light.css"
    },
    file: {
        defaultContent: content
    }
};

var editor = new EpicEditor(opts).load();

$('input[type="submit"]').click(function(e){
    $('input[type="hidden"]').val(editor.exportFile());
});
```

**Comment by OscarGodson** [comment]
Here, if you can get this to reproduce what you said I think I'll have something to be able to work off of:

http://jsbin.com/awecuh/1/edit

Tried again tho from this and still no luck, but I could be missing something.

**Comment by OscarGodson** [comment]
bump - Any updates?

**Comment by brentjanderson** [comment]
Not yet - I've been fiddling with your jsbin post but can't reproduce it there. I'm going to set up a demo using PHP and EpicEditor, as I think it has more to do with the server than EpicEditor. I still think this is a bug, since it is resolvable client-side, but the variable element in this problem seems to be the data's origin (Server-side vs. hard-coded in).

**Comment by OscarGodson** [comment]
Cool, yeah, sounds great. If you can get a repro case I'll knock this one out :)

**Comment by brentjanderson** [comment]
Well, I'm having a hard time reproducing this in PHP. If I find another way to isolate it through my own usage, I'll reopen. Otherwise this is a hard bug to nail down.

**Comment by OscarGodson** [comment]
@brentjanderson sounds good. Thank you for the update!
