### ISSUE TITLE
Adding support for Django

### ISSUE THREAD

**Issue by barraq** [OscarGodson/EpicEditor#211]
Hi all,

I just released an EpicEditor support for Django (a python web framework).
https://github.com/barraq/django-epiceditor

Best,
Rémi

![EpicEditor view within Django admin](https://f.cloud.github.com/assets/293498/184763/ba7ca12c-7cea-11e2-9585-660e7353c574.png)

**Comment by OscarGodson** [comment]
Über like! :thumbsup: Put it in: https://github.com/OscarGodson/EpicEditor/wiki/EpicEditor-Implementations which eventually I'm gonna move to the web site. Thanks!

**Comment by OscarGodson** [comment]
It appears that your repo will clone a copy of EpicEditor. So when a new version of EpicEditor is released new installs of your project will automatically be updated?

**Comment by barraq** [comment]
Hi Oscar,
Well at the current time yes... I I know this is not good :) but I looked for a specific "tag" branch for the 0.2.0 version of EpicEditor but it appears you don't have one yet... only a branch for the version 0.1.0 (which is quite old).
As soon as the 0.2.0 is released, stable and that you create a branch for it I will clone this "0.2.0" stable version.

What do you think?
I the meantime could you create a 0.2.0 branch with the current version of the master?

Let me know :)

**Comment by OscarGodson** [comment]
The 0.1.0 release branch shouldn't even be there. We use tags. Git pull, then git checkout 0.2.0 or whatever. Branches are meant to be deleted but not tags :)

**Comment by barraq** [comment]
Yup, I now use the tag 0.2.0 for the epiceditor ;)

**Comment by OscarGodson** [comment]
:thumbsup:
