### ISSUE TITLE
Chrome's last update broke fullscreen

### ISSUE THREAD

**Issue by OscarGodson** [OscarGodson/EpicEditor#216]
Waiting to hear back from the Chromium team, but it looks like some change broke fullscreen. [Here are the details.](https://code.google.com/p/chromium/issues/detail?can=2&q=fullscreen%20css&colspec=ID%20Pri%20Mstone%20ReleaseBlock%20OS%20Area%20Feature%20Status%20Owner%20Summary&id=181116&thanks=181116&ts=1362729888#makechanges).

Please star the issue!

cc: @paulirish

**Comment by Gankra** [comment]
This doesn't repro on epiceditor.com right now... fixed?

**Comment by balexand** [comment]
I'm still seeing this on the latest version of Chrome for Mac.

**Comment by OscarGodson** [comment]
I still see this as well. Depends on something but I'm not sure. Some people on the same version see this and some dont. Try Windows Chrome, @gankro. Or, try a beta or canary build. Also, starring or commenting on that issue helps, @balexand.

**Comment by Gankra** [comment]
Odd... alright. This is only for Chrome, yes? Not webkit or anything?

**Comment by OscarGodson** [comment]
Only Chrome I believe. Safaris full screen has been broken forever while FF and Chrome have always worked.

**Comment by Gankra** [comment]
Seems like native fullscreen is a total no-go for any production deployment, then?

**Comment by OscarGodson** [comment]
As of now, probably. It might have something to do with how they handle fullscreen and if they changed it from sync to async. All the fullscreen calculations may just need to be put in a callback. I'd love to see if I, or we, can try that and see if it fixes it and if so we can get it into 0.2.2 with the HTML pasting fix.

**Comment by MariusRumpf** [comment]
For me the fullscreen is only working when pasting the script at the bottom of the body. If I place it in the head chrome fullscreen isn't working.

**Comment by OscarGodson** [comment]
Thats strange. Ive never put epiceditor's script in the head. I actually never put any scripts except analytics in the head. Could you give me a test case to look at?

**Comment by MariusRumpf** [comment]
Browser: Chrome 27
System: OSX 10.8.3

Following code **doesn't** work

``` html
<html>
<head>
    <title>Test Case</title>
    <script src="js/epiceditor.min.js"></script>
    <script>var editor = new EpicEditor().load();</script>
</head>
<body>
    <div id="epiceditor"></div>
</body>
</html>
```

`Uncaught TypeError: Cannot read property 'webkitRequestFullScreen' of null`

This also **doesn't**\* work:

``` html
<html>
<head>
    <title>Test Case</title>
    <script src="js/epiceditor.min.js"></script>
</head>
<body>
    <script>var editor = new EpicEditor().load();</script>
    <div id="epiceditor"></div>
</body>
</html>
```

`Uncaught TypeError: Cannot set property 'innerHTML' of null`
This is cause the script executes directly after load.

Only this code does work:

``` html
<html>
<head>
    <title>Test Case</title>
    <script src="js/epiceditor.min.js"></script>
</head>
<body>
    <div id="epiceditor"></div>
    <script>var editor = new EpicEditor().load();</script>
</body>
</html>
```

So native full screen of Chrome can only be used if loaded at the bottom.

**Comment by Gankra** [comment]
I don't think this is really a bug with fullscreen, so much as assumptions epiceditor makes on the whole.

load()ing the editor before the DOM is properly "ready" will break stuff since we touch the DOM. There are various ways to allow the DOM to be ready, the most obvious/easy way being jquery's onready event. If you're not using jquery, then you can probably accomplish this with a settimeout, the browser onload event (which will occur sometime after jquery's ready), or, of course, putting the script at the end of the document .

Including scripts anywhere but at the end of the document is generally considered bad practice (the page displaying gets blocked by your script executing), so I wouldn't consider this a substantial problem.

**Comment by OscarGodson** [comment]
@Gankro you're replying to @MariusRumpf, right? For me it happens on epiceditor.com which is on the bottom. I don't know why this particular case isn't working, but half the people I know have this problem, unfortunately.

**Comment by OscarGodson** [comment]
I played with this even more. I tried putting _all_ the calculation code in the `webkitfullscreenchange` event and still no go. I then, inside the webkitfullscreenchange event, added a `setTimeout` of 1. Still nothing. I then bumped that to 1000 and voila it works. That's a really shitty hack tho and I'd rather not put a _full second_ timer on it to make it work.

**Comment by OscarGodson** [comment]
I committed my nasty hack for this. Don't like it, but it'll have to do for now.

**Comment by OscarGodson** [comment]
Due to the timeout I had to implement a callback for enter and exit fullscreen and also udpated the tests and docs. This, however, basically breaks an API (changes it from sync to async), so the version bumb has to be a 0.3.0.
