### ISSUE TITLE
Textarea and convert

### ISSUE THREAD

**Issue by Freyskeyd** [OscarGodson/EpicEditor#217]
Yo,

I try to use EpicEditor on my blog, but i can use it to create new post.
In  on.('save') i replace the content of a textarea with current exportFile().
But when i edit it later (with HTML), html is not convert to markdown...

is it missing feature or i use it badly?

thank's

**Comment by OscarGodson** [comment]
EE has a markdown parser but not an html to markdown converter. That's a really tough problem and most (all?) editors dont do this. HTML parsing is hard and JS isn't good at it.

Instead, you should save both formats to your DB. So, in your DB you'd have like content_markdown and content_html. Does that make sense?

**Comment by Freyskeyd** [comment]
Yep,
that's what i do for the moment.
Thank's

Closed
