### ISSUE TITLE
Allow split editor/preview in non-fullscreen

### ISSUE THREAD

**Issue by ngryman** [OscarGodson/EpicEditor#218]
Hi,

I love the fullscreen feature, and particularly the split mode.
But sometimes, while I'm writing I like browsing to search for references, etc ...
The fullscreen mode is well adapted for kinda `zen mode` situations but not adapted for writing and actively searching.

Could you add a simple split mode wo/ fullscreen?

Thanks.

EDIT:

Oups, my mistake, it's possible w/ the `useNativeFullscreen: false` option...
I would recommend to update either the documentation or the option name because I did not understand that.
Perhaps something like `fullscreenSplit: false` would be better.

**Comment by OscarGodson** [comment]
Such as searching the web and using different apps and stuff, or searching the same page? If its the first thing, could you set nativeFullscreen to false?

**Comment by ngryman** [comment]
Yeah sorry, I did not understand the option correctly (cf. edit).

**Comment by OscarGodson** [comment]
The problem with your suggestion is that it wont ever work in IE, Opera and older Firefox versions so the option would be meaningless. Maybe just a documentation update? Also changing the param name would break people's apps on updating. I'll take a pull request tho if you have any suggestions for documentation fixes or anything else :)
