### ISSUE TITLE
Doesn't work in jqueryui dialog

### ISSUE THREAD

**Issue by relipse** [OscarGodson/EpicEditor#221]
The epiceditor is great! I want to use it in my boss's bugtracking website, but I found out it doesn't work in a jqueryUI dialog box

You can see the behavior by simply adding a jqueryui dialog and putting an epic editor in the html inside the dialog

You can also see this behavior at http://jim.clearbugs.com org: testtest user: testtest pw: testtest

Wait 10 seconds and click "Add bug"
Thanks
Jim

**Comment by OscarGodson** [comment]
Works for me :)

http://jsbin.com/ocuteb/1/edit

I took a quick look at your code and it looks like you're loading epiceditor into some div that's hidden and then you're asking jQuery UI to take that and create div's HTML and put it into the modal. That wont work for a variety of reasons including the fact that none of the events are hooked up. You're basically just copying and pasting HTML from the div into jquery UI's div. 

You need to be instantiating a new EpicEditor instance each time the modal opens. The above link goes to a super simple, working demo. Let me know if you need more help.

P.S. you should really move all your JS to the bottom of the page and then you wouldn't need the `$(function () {})` stuff ;)

**Comment by relipse** [comment]
Great! Thanks
