### ISSUE TITLE
need .focus() method

### ISSUE THREAD

**Issue by relipse** [OscarGodson/EpicEditor#223]
I am trying to set focus right when the user opens a bug
currently I am using this code:

```
epicAddEditBug.editorIframeDocument.body.focus();
```

but I suppose it is better to add a .focus() method?

**Comment by OscarGodson** [comment]
This is a good idea. I'll try to get it into the next release. Until then, does `focusOnLoad: true` not work for you in your case?

**Comment by relipse** [comment]
no it didn't work so i had to do a combination of both:

```
        open: function (ev, ui) {
          if (epicAddEditBug){
             //already loaded, go ahead and focus it
             epicAddEditBug.editorIframeDocument.body.focus();
          }else{
             epicAddEditBug = new EpicEditor(epicAddEditBugOpts);
          }
          epicAddEditBug.load();
           },
```

...your quick responses are very nice by the way, thank you

**Comment by OscarGodson** [comment]
I'd have to try this, but triggering `.edit()` should make it focus:

https://github.com/OscarGodson/EpicEditor/blob/develop/src/editor.js#L1194

That should work. Let me know if it doesn't. If it doesn't I think it's this issue:

https://github.com/OscarGodson/EpicEditor/issues/134

Which is because IE wants to focus on the iframe and FF/Chrome wants to focus on the body.

**Comment by OscarGodson** [comment]
OK, you can see commit 531a978 above. It's not in develop yet as I need to write tests and docs for it before, but this allowed me to fix another bug too so I'll just get it into this release.

**Comment by relipse** [comment]
Thank you very much, let me know when the release is up and ready (or is there a way i can get a notification?)
Jim

**Comment by OscarGodson** [comment]
When I close this issue and/or comment you will get an email notification unless you've manually unwatched this thread. :)

**Comment by OscarGodson** [comment]
This is now in develop. Let me know if it works well! You can now just call `editor.focus()` whenever you want.
