### ISSUE TITLE
loading as Â chars?

### ISSUE THREAD

**Issue by relipse** [OscarGodson/EpicEditor#224]
I didnt search for a duplicate, but every time I load text I am getting weird chars for example

```
Do your homework?
```

turns into

```
DoÂ yourÂ homework?
```

using the code

```
epicAddEditBug.importFile(null,bug.memo);
```

**Comment by OscarGodson** [comment]
If you type the bug.memo text into importFile manually, does it do the same thing?

**Comment by relipse** [comment]
Yes Oscar,

```
function dlgAddEditBug(bug){
   bug = bug || {};
   frmAddEditBug_Set(bug);
   $('#dlgAddEditBug').dialog('open');
   if (epicAddEditBug){
     epicAddEditBug.edit();
     epicAddEditBug.importFile(null,'bug memo test');
  }
}
```

turned up as this in the epic editor, its been a problem since i first started using it, never fixed it...

```
bugÂ memoÂ test
```

**Comment by relipse** [comment]
I just checked on FF, it works ok,
This is happening on Chrome Version 26.0.1410.64 m Win 7 and MacOS

**Comment by OscarGodson** [comment]
@relipse I can't reproduce this on my end:

![](http://f.cl.ly/items/0Q3l112C0D291L2q3A1X/Screen%20Shot%202013-04-19%20at%2011.54.23%20PM.png)

Can you reproduce the issue in a JSBin or something so I have something to work off of? http://jsbin.com/ocuteb/2/edit

**Comment by relipse** [comment]
i fixed it with 

```
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
```
