### ISSUE TITLE
unneeded margin?

### ISSUE THREAD

**Issue by relipse** [OscarGodson/EpicEditor#225]
I am getting a margin in preview mode that seems to be about 20 pixels but I can't seem to get rid of it. Any help?

**Comment by OscarGodson** [comment]
More than what's on EpicEditor.com? Do you have a screenshot?

**Comment by OscarGodson** [comment]
Or link? Can't help without something to look at :)

**Comment by OscarGodson** [comment]
The text was are garbled and just said [image 1]. Could you retry? Did you try to send an attachment via email?

**Comment by relipse** [comment]
Yeah email

**Comment by OscarGodson** [comment]
Anyway to get that info?

**Comment by relipse** [comment]
Sorry for the delay, here is the example of the margin which imo should be 0
http://i.imgur.com/6XP7Dtn.png

**Comment by OscarGodson** [comment]
Hmm, looks like there's no CSS loading. If there's no CSS loading the `<iframe>`'s will have default browser margin/padding on the `html` and `body`. Are you sure the CSS is loaded?

**Comment by OscarGodson** [comment]
It's been awhile. closing for now. If you're still having this problem or have more information feel free to reopen.
