### ISSUE TITLE
Table not working

### ISSUE THREAD

**Issue by cjloong** [OscarGodson/EpicEditor#244]
Hi
I am not able to get table to render properly.
Table col  | col 2
---------- | ---------
 test      | test

does not work.

**Comment by OscarGodson** [comment]
Are you on 0.2.0 or older or 0.2.1?

**Comment by OscarGodson** [comment]
FWIW your table isn't working on GitHub either it looks like.

**Comment by cjloong** [comment]
Was working on it in http://epiceditor.com/

Anyway, this is a different table which I tried in github.

| Left align | Right align | Center align |
| :-- | --: | :-: |
| This | This | This |
| column | column | column |
| will | will | will |
| be | be | be |
| left | right | center |
| aligned | aligned | aligned |

Or this simpler one
| Test | Test |
|------|------|
| col 1 | col 2 |

**Comment by OscarGodson** [comment]
epiceditor.com is 0.2.0. Tables weren't supported until 0.2.1. I'm literally working on getting 0.2.1 released tonight. Hopefully your test will work by tomorrow :)

**Comment by cjloong** [comment]
Thanks. But no worries, just take your time. ;-)

**Comment by OscarGodson** [comment]
The site is now updated with 0.2.1. Your working table above now also works on the epiceditor.com

Cheers!
