### ISSUE TITLE
periods in exported text after it saves to server

### ISSUE THREAD

**Issue by ghost** [OscarGodson/EpicEditor#252]
Sorry admin, the problem was in the markdown parser on the server side. I make some changes from the original js of epic editor to include in my cms, sorry and thanks for the reply.

**Comment by OscarGodson** [comment]
Hmm never seen that before. I need more info tho:
1. What version of EpicEditor are you using? (If you dont know type EpicEditor.version into the JS console).
2. Does this happen in all browsers?
3. Are the dots after or before the data hits the server. I.e. do you see them in your POST request data, or not then, but after its in your DB, or, not either, and its in your GET request from the DB?
4. can i see your EpicEditor code including the stuff that saves and retrieves from the server?

**Comment by OscarGodson** [comment]
Going to close this since there hasn't been a reply in over 5 days. Reopen if you are still having this issue.
