### ISSUE TITLE
Can't get the textarea to sync

### ISSUE THREAD

**Issue by kaihendry** [OscarGodson/EpicEditor#253]
https://github.com/kaihendry/wordsister/blob/epiceditor/edit/index.php#L48

What am I missing? Many thanks!

**Comment by OscarGodson** [comment]
I dont see anything wrong off the bat. I'll take a look more when I'm at a computer, but a few questions:
1. What browser / os
2. Are there any JS errors?
3. If you remove the 2nd textarea, does that fix it?
4. What version of EpicEditor? (if you dont know type EpicEditor.version into the JS console)

**Comment by OscarGodson** [comment]
One thing I see is you have your JS in the head. All JS (except rare cases) should be in the body right above the body closing tag. This could cause issues because the DOM doesnt exist when EpicEditor loads.

**Comment by kaihendry** [comment]
Decided to go for showdown for my project. Thanks!

**Comment by OscarGodson** [comment]
Huh? Showdown is a Markdown parser, EpicEditor is a text editor. What do you mean?

**Comment by kaihendry** [comment]
I'm using this: http://markdown.pioul.fr/

**Comment by tillcarlos** [comment]
@kaihendry Same here. Thanks for the tipp! epiceditor looks nicer integrating it into rails in combination with this was too much right now. Also I needed the two-column version with preview (i know that this would be possible to do with epici).

I am thinking about making minimalisteditor-rails gem. If there are other people interested, let me know!

Anyway: Thanks to the epiceditor guys! You are doing awesome work here!

**Comment by OscarGodson** [comment]
You put your JS in the head too? Not much EpicEditor can do from it's side to fix that :P

**Comment by AJ-Acevedo** [comment]
@tielefeld If you like EpicEditor and are looking for a Rails Markdown editor, I just started developing [EpicEditor for Rails](https://github.com/ajalabs/epiceditor). The plan is to easily added EpicEditor to the asset pipeline and some view helpers which allow you to easy embed EpicEditor using ruby code. If you're interested, contributions are welcome.
