### ISSUE TITLE
When using 2 EpicEditors with TwitterBootstrap tabs height of 2nd editor is 0 

### ISSUE THREAD

**Issue by go13** [OscarGodson/EpicEditor#255]
in the following bloc the second editor is not visible. I am using tabbable from here http://twitter.github.io/bootstrap/components.html#navs

```
<script src="/static/epiceditor/js/epiceditor.js"></script>

<style>
#t1, #t2{
    height : 220px;
}
</style>

<div class="tab-content">       
        <div class="tab-pane active" id="tab2">
          <div id="quiz-navigator" class="tabbable tabs-right" >      
            <ul id="tabs" class="nav nav-tabs">     
                <li class="active">
                    <a href="#t1" data-toggle="tab">Question</a>
                </li>
                <li>
                    <a href="#t2" data-toggle="tab">Question 2</a>
                </li>
            </ul>   
            <div id="tabs-container" class="tab-content" style="box-sizing: border-box">            
                <div id="t1" class="tab-pane active">
                </div>
                <div id="t2" class="tab-pane" style="box-sizing: border-box">
                </div>
            </div>  
          </div>
        </div>

      </div>

<script>
function ld(c){ 
var opts = {
          container: c,
          textarea: null,
          basePath: '/static/epiceditor',
          clientSideStorage: true,
          localStorageName: 'epiceditor',
          useNativeFullscreen: true,
          parser: marked,
          file: {
            name: "texteditor"+c,
            defaultContent: '',
            autoSave: 100
          },
          theme: {
            base: '/themes/base/epiceditor.css',
            preview: '/themes/preview/preview-dark.css',
            editor: '/themes/editor/epic-light.css'
          },
          button: {
            preview: true,
            fullscreen: true
          },
          focusOnLoad: false,
          shortcut: {
            modifier: 18,
            fullscreen: 70,
            preview: 80
          },
          string: {
            togglePreview: 'Toggle Preview Mode',
            toggleEdit: 'Toggle Edit Mode',
            toggleFullscreen: 'Enter Fullscreen'
          }
    };
    var editor = new EpicEditor(opts);
    editor.load();
    return editor;
}
var e1 = ld("t1");
var e2 = ld("t2");

</script>
```

**Comment by OscarGodson** [comment]
I took your exact code and put it into an HTML page and it works fine for me in Chrome and Firefox.

![](http://dl.dropbox.com/u/135095/Screenshots/04.png)

Is it something to do with your other JS? If you remove all your other JS does it work? What version of EE are you using and what browser + OS?

**Comment by OscarGodson** [comment]
Also I've never used any Twitter bootstrap stuff. Doesnt sound like a bug with epiceditor but just an implementation problem. Since I dont have any experience with Twitter bootstrap JS modules you are better off posting this question  here with our support partner who can help you with implementing this: http://codersclan.net/forum/index.php?repo_id=2

**Comment by ThatRendle** [comment]
Oscar,

The supplied markup won't reproduce the problem because it's not referencing the Bootstrap JS. When that JS is present the second tab is hidden at the point the EpicEditor is created, which results in the width and height of various iframes and divs within the editor being set to 0px, I'm guessing because that's the value being returned when you grab the width and height of the div container.

**Comment by ThatRendle** [comment]
For reference, I worked around this by running this code in the callback that Bootstrap tabs fire when they are selected:

```
    public reflowEpicEditors() {
      $(".epic-editor").height(220).each((index: number, elem: Element) => {
        var $elem = $(elem);
        var epicEditor = $elem.data("epicEditor");
        epicEditor.reflow();
      });
    }
```

Obviously this requires the class `epic-editor` to be applied to all EpicEditor containers, and I set the `epicEditor` data on the element when I create the editors.

(Oh, and the code is in TypeScript, which is awesome. Yes it is.)

**Comment by OscarGodson** [comment]
Thanks @markrendle, this makes sense and will probably be useful to others. Yeah, EpicEditor wouldn't ever know when the height of it's container changes without some kind of timer which would be gross. Your solution seems great.

And, I was wondering what that code was ;)
