### ISSUE TITLE
[QUESTION] EpicEditor as viewer

### ISSUE THREAD

**Issue by valx76** [OscarGodson/EpicEditor#256]
Hi,

I would like to know if it's possible to use EpicEditor as **viewer** only ?

My case is the following :
- I'm using EE (editor) as a comment section
- The Markdown code is saved in a database

Now, the comments have Markdown code inside, and I would like to use the EE parser to render it, without an editor..

Thanks !

**Comment by OscarGodson** [comment]
It might be better for performance and faster load to just use Marked (our MD parser) and the preview CSS and put the MD into a comment area in a simple div. But to hack EpicEditor into a viewer, this should work (remember, for each comment this will create 3 iframes):

``` js
  var editor = new EpicEditor({
    button: false
  }).load().preview();
```

P.S. marked is just included on your page when you include EpicEditor. Here's the docs for marked: https://github.com/chjj/marked

**Comment by valx76** [comment]
Right, 3 iframes for each comment, that's heavy..
I'll change the code or use the Marked parser.

Thanks for your answer Oscar !
