### ISSUE TITLE
Asset fingerprinting

### ISSUE THREAD

**Issue by pbougie** [OscarGodson/EpicEditor#259]
Using the Rails asset pipeline with [asset fingerprinting](http://guides.rubyonrails.org/asset_pipeline.html#what-is-fingerprinting-and-why-should-i-care-questionmark) is difficult with EpicEditor's current setup. I was able to include the CSS theme files by using the following configuration:

``` javascript
var opts = {
  basePath: '',
  theme: {
    base: "<%= asset_path 'epiceditor/epiceditor.css' %>",
    editor: "<%= asset_path 'epiceditor/epic-dark.css' %>",
    preview: "<%= asset_path 'epiceditor/github.css' %>",
  },
}
```

Filename extension is `.js.erb` so that it is first parsed by ERB and results in (fingerprints are based on file contents):

``` javascript
var opts = {
  basePath: '',
  theme: {
    base: "/assets/epiceditor/epiceditor-fe29664b99583cb091b9736a620b1aa2.css",
    editor: "/assets/epiceditor/epic-dark-e011369dac6ce0e33adfa283509a95bd.css",
    preview: "/assets/epiceditor/github-00404a923df019f174b8e68c117b75ef.css",
  },
}
```

The 3 images don't work with asset fingerprinting because the paths and filenames are hard-coded in the JavaScript. The solution I used was to change the button tags to <span> tags and embed the images as base64 encoded background images in the CSS file. Seems to work very well. Also reduces number of HTTP requests.

I'd like to submit a pull request to get this in the main project so I don't have to maintain this manually every time I update the library in my project.

Let me know what you think.

**Comment by OscarGodson** [comment]
Im not sure how well basr64ing works in IE9-10, also it makes it more of a pain to swap out images when people want their own icon. However, we'd love a PR for whatever to make it work better with Rails. I'm not sure what you have in mind, but we're open to any ideas as long as it keeps it easy to setup and doesn't break previous versions too badly.

Let me know! This would be awesome to get fixed!

**Comment by OscarGodson** [comment]
@pbougie Can this ticket be closed or is there some more CSS / theme work that has to be done?

**Comment by OscarGodson** [comment]
Can you reopen and update the description of the ticket if there's still work to be done tho?

**Comment by pbougie** [comment]
No, these changes make it much easier to work with the Rails asset pipeline or similar. No source files need changing anymore which was the point. Thanks.
