### ISSUE TITLE
Uncaught TypeError: Object #<Object> has no method 'replace'

### ISSUE THREAD

**Issue by azhang** [OscarGodson/EpicEditor#261]
I'm getting

```
Uncaught TypeError: Object #<Object> has no method 'replace'
Please report this to https://github.com/chjj/marked. 
```

for `Lexer.prototype.lex`

**Comment by azhang** [comment]
Ok, I figured it out. There is no documentation for using this with requirejs, so I had been trying to require it with name "EpicEditor". turns out it needs to be "marked". I'm going to make another Issue with a request to add this into documentation.

**Comment by OscarGodson** [comment]
FYI for people who see this ticket looking for how to get it to work with RequireJS:  https://github.com/OscarGodson/EpicEditor/wiki/EpicEditor-with-Module-Loaders
