### ISSUE TITLE
syncing EpicEditor with textarea, with "keyup" event

### ISSUE THREAD

**Issue by azhang** [OscarGodson/EpicEditor#263]
I spent forever trying to get a character counter working with EpicEditor. I don't know if this will be useful for a lot of people, but I just modified EpicEditor to fire a "keyup" event whenever it syncs with the textarea, Keyup is the most common event used for all character counters, I think.
I added the following to `EpicEditor.prototype._setupTextareaSync` under `syncTextarea`:

```
  var event;
  var eventName = "keyup";
  if (document.createEvent) {
    event = document.createEvent("HTMLEvents");
    event.initEvent(eventName, true, true);
  } else {
    event = document.createEventObject();
    event.eventType = eventName;
  }

  event.eventName = eventName;
  event.memo = {};

  if (document.createEvent) {
    self._textareaElement.dispatchEvent(event);
  } else {
    self._textareaElement.fireEvent("on" + event.eventType, event);
  }
```

**Comment by OscarGodson** [comment]
Why cant you use the change event?

**Comment by azhang** [comment]
Change event only fires on 'blur', doesn't it?

**Comment by OscarGodson** [comment]
Oops, sorry, I mean `update`:

http://epiceditor.com/#events

> Fires whenever a file is updated.

**Comment by azhang** [comment]
ahh, yes! I misunderstood the meaning of "save". I thought it meant saving to localstorage.

Thanks!

```
  editor.on('update', function(){
    $(textarea).trigger('keyup');
  });
```

**Comment by OscarGodson** [comment]
:thumbsup:

**Comment by Kryptonit3-zz** [comment]
Does this also work for pastes?

**Comment by OscarGodson** [comment]
@Kryptonit3 "update" in EpicEditor works by doing a a diff every 100ms by default, so a paste should still trigger an update.
