### ISSUE TITLE
Chrome and IE9-10 replacing all spaces with &nbsp;

### ISSUE THREAD

**Issue by Gankra** [OscarGodson/EpicEditor#268]
I don't know what happened, but suddenly every instance of EpicEditor (master, develop, my own fork) I look at now has this bug:
- Type in some text into epic editor
- Refresh
- Inspect DOM; All spaces are now `&nbsp;`

This really screws the word-wrapping, making the content hideous, to say the least.

@OscarGodson are you seeing this too?

Chrome 28.0.1500.71
OSX 10.8.4

Not reproducing in Safari/FF.

Really hoping my Chrome install is broken or something.

**Comment by Gankra** [comment]
Just reproduced in a brand-new install of Chrome 28.0.1500.72 m in a basically clean Windows 7 Enterpise SP1 VM.

Fuck.

**Comment by Gankra** [comment]
Did some quick hacking, this seems to work:

```
@@ -168,7 +168,8 @@
     // If you want to know why we check for typeof string, see comment
     // in the _getText function
     if (typeof document.body.innerText == 'string') {
-      content = content.replace(/ /g, '\u00a0');
+      content = content.replace(/\s\s/g, '\u00a0 ');
+      content = content.replace(/\s\s\s/g, '\u00a0 \u00a0');
       el.innerText = content;
     }
     else {
```

**Comment by Gankra** [comment]
Hmm, no that screws up \n\s, working on it...

**Comment by Gankra** [comment]
```
@@ -168,7 +168,10 @@
     // If you want to know why we check for typeof string, see comment
     // in the _getText function
     if (typeof document.body.innerText == 'string') {
-      content = content.replace(/ /g, '\u00a0');
+      content = content.replace(/\n /g, '\n\u00a0');
+      content = content.replace(/[ ][ ][ ]/g, '\u00a0 \u00a0');
+      content = content.replace(/[ ][ ]/g, '\u00a0 ');
       el.innerText = content;
     }
     else {
```

Seems to work well. [ ] is just a space, formatted so the linter doesn't freak out.

**Comment by OscarGodson** [comment]
Problem with this is the damn minifier stripping those `\u00a0` out. Do you know of another good, trustworthy linter? What happens to Chrome if you make it use Firefox's text formatting (the `else` block)? Does it blow up there too?

I trust that you see this issue and this fixes it. I've been having issues with this chunk of code forever. It's probably time to write tests for it. If you dont want to for this ticket thats fine, I can handle it in a new ticket, but just let me know.

**Comment by Gankra** [comment]
Sorry, I don't know anything at all about minifiers/linters.

The patch I posted definitely passes all the adhoc tests I did for the Firefox fix for this same problem:
- First character is space <-- just added this one, neither chrome nor firefox actually pass this!
- Two spaces
- Three spaces
- Four spaces
- \n + space
- \n\n\n
- space + \n

Those are the weird corner cases

**Comment by Gankra** [comment]
```
@@ -168,7 +168,11 @@
     // If you want to know why we check for typeof string, see comment
     // in the _getText function
     if (typeof document.body.innerText == 'string') {
-      content = content.replace(/ /g, '\u00a0');
+      content = content.replace(/\n /g, '\n\u00a0');
+      content = content.replace(/[ ][ ][ ]/g, '\u00a0 \u00a0');
+      content = content.replace(/[ ][ ]/g, '\u00a0 ');
+      content = content.replace(/^ /, '\u00a0');
+
       el.innerText = content;
     }
     else {
@@ -185,6 +189,8 @@
       content = content.replace(/<br>\s/g, '<br>&nbsp;')
       content = content.replace(/\s\s\s/g, '&nbsp; &nbsp;')
       content = content.replace(/\s\s/g, '&nbsp; ')
+      content = content.replace(/^ /, '\u00a0')
```

This one fixes the first test I mentioned above.

**Comment by Gankra** [comment]
Tried your simplification recommendation:

```
@@ -165,28 +165,22 @@
   }

   function _setText(el, content) {
-    // If you want to know why we check for typeof string, see comment
-    // in the _getText function
-    if (typeof document.body.innerText == 'string') {
-      content = content.replace(/ /g, '\u00a0');
-      el.innerText = content;
-    }
-    else {
-      // Don't convert lt/gt characters as HTML when viewing the editor window
-      // TODO: Write a test to catch regressions for this
-      content = content.replace(/</g, '&lt;');
-      content = content.replace(/>/g, '&gt;');
-      content = content.replace(/\n/g, '<br>');
-      
-      // Make sure to there aren't two spaces in a row (replace one with &nbsp;)
-      // If you find and replace every space with a &nbsp; text will not wrap.
-      // Hence the name (Non-Breaking-SPace).
-      // TODO: Probably need to test this somehow...
-      content = content.replace(/<br>\s/g, '<br>&nbsp;')
-      content = content.replace(/\s\s\s/g, '&nbsp; &nbsp;')
-      content = content.replace(/\s\s/g, '&nbsp; ')
-      el.innerHTML = content;
-    }
+    // Don't convert lt/gt characters as HTML when viewing the editor window
+    // TODO: Write a test to catch regressions for this
+    content = content.replace(/</g, '&lt;');
+    content = content.replace(/>/g, '&gt;');
+    content = content.replace(/\n/g, '<br>');
+    
+    // Make sure to there aren't two spaces in a row (replace one with &nbsp;)
+    // If you find and replace every space with a &nbsp; text will not wrap.
+    // Hence the name (Non-Breaking-SPace).
+    // TODO: Probably need to test this somehow...
+    content = content.replace(/<br>\s/g, '<br>&nbsp;')
+    content = content.replace(/\s\s\s/g, '&nbsp; &nbsp;')
+    content = content.replace(/\s\s/g, '&nbsp; ')
+    content = content.replace(/^ /, '&nbsp;')
+
+    el.innerHTML = content;
     return true;
   }

```

Seems to work alright in FF and Chrome, passes all the eyeball tests noted.

**Comment by Gankra** [comment]
Other test worth adding with these spacing tests: `editor.exportFile().indexOf(" ")>-1`

**Comment by Gankra** [comment]
Confirmed FF/Chrome/Safari/IE10 unit tests all still pass.

This is the patch I will offer up for the situation. If you want to write proper unit tests I encourage it, but I'm unlikely to do it myself (I'm really, really bad at writing them).

**Comment by Gankra** [comment]
Basically the things you need to confirm in a unit test for this kind of thing is that there are no two plain spaces in a row, and no line starts with a plain space. Also between any two blocks of "real" characters, there should be at least one "real" space. E.G. every space in `hello     there` shouldn't become a non-breaking space. 

_ideally_ the spaces right after and before a word should be prioritized to be real spaces to optimize wrapping, but that's impossible in general (see: exactly two spaces in a row).

**Comment by OscarGodson** [comment]
Can you send a PR so I can test it out later?

**Comment by OscarGodson** [comment]
What exactly is the problem. I can't see any difference between your branch and develop:

![51e4e05be4b0e89eb246981a](https://f.cloud.github.com/assets/20615/802895/a70446e6-eddc-11e2-9d2c-327485a67b63.png)

Before I can really test it I need to know, other than the fact that behind the scenes it's using nbsp instead of raw spaces, whats the issue? Seems to save spacing the same in both cases identically.

**Comment by OscarGodson** [comment]
^ both of those are after refreshing the page with content too

**Comment by Gankra** [comment]
Before refreshing:
![before](https://f.cloud.github.com/assets/1136864/804958/18fd23a8-ee1e-11e2-8ebb-34089dbb74f1.png)

All good!

After refreshing:
![after](https://f.cloud.github.com/assets/1136864/804957/18f502ea-ee1e-11e2-9b13-ae41c40791a9.png)

Oh god everything is all-one-word!

**Comment by Gankra** [comment]
Replacing every space with a non-breaking space _is_ what your code current does for Chrome. That _can't_ have ever been correct behaviour, can it? Regardless, it seems that something has flipped somewhere, causing this to become really broken now.

**Comment by OscarGodson** [comment]
@Gankro Let me play with it again. No, the original code was to replace every other space with a `\u00a0` character I think.

**Comment by Gankra** [comment]
Which is a non-breaking space: http://www.fileformat.info/info/unicode/char/a0/index.htm

**Comment by Gankra** [comment]
Fixed!
