### ISSUE TITLE
Can't get EpicEditor to save file on server

### ISSUE THREAD

**Issue by ghost** [OscarGodson/EpicEditor#270]
Hi. I'm trying to get EpicEditor to save the contents of the `div` to the server. As I understand it from the docs, the script should do this automatically by autosaving every 100 ms, but I can't find the file on my server after using EpicEditor. Here's my code:

```
<div id="epiceditor"></div>
<script src="epiceditor/js/epiceditor.min.js"></script>
<script>
  var opts = {
    container: 'epiceditor',
    basePath: 'epiceditor',
    file: {
      name: 'fileName',
      autoSave: 100,
    },
    theme: {
      base: '/themes/base/epiceditor.css',
      preview: '/themes/preview/github.css',
      editor: '/themes/editor/epic-light.css'
    },
    focusOnLoad: false
  }
  var editor = new EpicEditor(opts).load();
</script>
```

So, shouldn't a md file, `fileName.md` be showing up in my `./epiceditor` directory? Do I have to turn off local storage for this to work?

Thanks.

**Comment by OscarGodson** [comment]
No, it's localStorage, not computer file storage. Client side JavaScript does not have access to your file system (that'd be pretty scary). By file we mean a localStorage file (in your console if you type `localStorage.epiceditor` you'll see the file contents, the modified date, and created date. It's up to you if you want to store the file as a plain text file. Most people store the "file" contents in a database, not a static file, but either is possible.
