### ISSUE TITLE
loading more than one editor at a time

### ISSUE THREAD

**Issue by anibalgomezprojects** [OscarGodson/EpicEditor#272]
I am implementing multil-language support, is there a way to load more than one epiceditor at a time? i can't load more than 1

**Comment by OscarGodson** [comment]
Should be as simple as:

``` js
var editor1 = new EpicEditor({ container: 'foo' });
var editor2 = new EpicEditor({ container: 'bar' });
```

Example to JSBin in the comments here: https://github.com/OscarGodson/EpicEditor/issues/138

Closing, but feel free to reopen if for some reason this isn't working.
