### ISSUE TITLE
Update Uglify or switch to prevent it removing whitespace characters

### ISSUE THREAD

**Issue by OscarGodson** [OscarGodson/EpicEditor#273]
Right now, each time we minify uglify is removing whitespace characters. We need to fix this for the next release.

**Comment by Gankra** [comment]
It's just the one \u00a0 in _sanitizeRawContent now, right? That seems to be preserved because it's in a regex. While the core problem persists, it's a non-issue for our source now.

**Comment by OscarGodson** [comment]
I'm not sure what you mean exactly. Its not preserved, that's the problem. When you run uglify it strips those out making new docs have weird characters. When you say "our source", do you mean EpicEditors or your project at work?

**Comment by Gankra** [comment]
Epic Editor's. The min.js of the latest development (remember, I just removed a lot of the unicode references to whitespace) seems to have all the whitespace characters I expect. Which are gone?

**Comment by OscarGodson** [comment]
Oh, I didn't realize you removed that line completely. OK, closing :)
