### ISSUE TITLE
Editor doesn't show up for bootstrap modals

### ISSUE THREAD

**Issue by pangwa** [OscarGodson/EpicEditor#275]
I want to use the editor in bootstrap modal. But it won't show up..
This seems to be some css issue as it works well with bootstrap collapse divs

**Comment by OscarGodson** [comment]
What's your code? I dont use bootstrap, but I can assume it takes some Dom element and copies it as the content to a modal div and then displays it? Or, does it use some string in a JS call? I'd like to see the bootstrap code and editor code you have.

**Comment by pangwa** [comment]
Hi,

Please check attached demo files.

> thanks,
> --pangwa--

**Comment by pangwa** [comment]
It seems not able to attach zip files.

Below is the html code I used to display modals and epiceditor.

``` html
 <div class="container">
      <h1>S-Notes</h1>
      <form class="form-horizontal">
        <fieldset></fieldset>
        <div class="control-group">
          <div class="controls">
            <input id="search-input" placeholder="Search by title, content, tags">
            <button type="submit" id="search" class="btn"><i class="icon-search"></i></button>
            <button href="#addNotePanel" data-toggle="modal" class="btn"><i class="icon-plus"></i></button>
          </div>
        </div>
      </form>
      <div id="addNotePanel" class="modal hide fade" style="height: auto;">
        <form id="addNoteForm" method="post" action="/ class="form-borizontal">
          <div class="control-group">
            <label class="control-label">Content</label>
            <div class="controls">
              <div id="epiceditor" style="height: 155px;"><iframe scrolling="no" frameborder="0" id="epiceditor-35004" style="width: 760px; height: 155px;"></iframe></div>
              <textarea id="noteContent" name="content" placeholder="Note content" style="display:none"></textarea>
            </div>
          </div>
          <div class="control-group">
            <div class="controls">
              <button type="submit" id="noteSubmit" class="btn btn-primary">Add</button>
              <button href="#addNotePanel" data-toggle="modal" class="btn btn-danger"> Cancel</button>
            </div>
          </div>
        </form>
      </div>
```

I also added one line of js code to init the editor after page loade

``` js
var editor = new EpicEditor().load();    
```

**Comment by OscarGodson** [comment]
Is the iframe in there from your or is this just generated HTML? (I'm assuming it's generated HTML).

Yeah, so the issue is that EpicEditor _is_ on the page and it's associated to #epiceditor there, but Bootstrap takes the HTML and puts it inside of a new div. There's nothing I can do from my side since they're copying the DOM. What I think you need to do instead is see if Bootstrap has a callback or event you can hook into and do something like:

``` js
$('#myModal').on('shown', function () {
  var editor = new EpicEditor({ container: $(this).find('.epiceditor')[0] }).load();
})
```

**Comment by pangwa** [comment]
Ok, I see. Thanks

**Comment by qishen** [comment]
The above solution works for me, but when I was trying to show Modal window after EpicEditor finishes loading, It fails to render the editor on Modal window, so I inspect all DOM elements and find out the whole editor wrapped in iframe is already inserted into my specified container. Any ideas on this problem?

``` javascript
this.editor.load(function(){
    self._dialog.modal('show');
});
```
