### ISSUE TITLE
autogrow doesn't open at the right height and prevents scrolling on load in Firefox

### ISSUE THREAD

**Issue by OscarGodson** [OscarGodson/EpicEditor#279]
In Firefox (doesn't seem to happen in IE9 or Chrome) if you have autogrow on, type more content then the minHeight and then refresh the editor doesn't open to the height of the content. Instead, it seems, to open to the minHeight. You are unable to scroll in the editor as well. Only way to "fix" this from the user end is to select all or to start typing.

**Comment by Gankra** [comment]
Hmm, I had thought that the setTimeouts had fixed this. Perhaps cranking up the timeouts will suffice...? Will look into it this weekend.

**Comment by Gankra** [comment]
To be clear, this is basically a consequence of Firefox lazily determining the necessary height to contain all the text in a document. I could not find any solid way to force it to compute this value in a synchronous manner.

**Comment by OscarGodson** [comment]
Maybe this is a Firefox 23 bug? Maybe see if you can repro in 23 but not 22 or 21?

**Comment by Gankra** [comment]
Oh man, sorry I totally forgot about this. This issue definitely isn't reproducing for me on epiceditor.com. Possibly just because my machine is fast enough to get in under the setTimeout limit?

**Comment by Gankra** [comment]
Does this patch fix the issue for you? https://github.com/Gankro/EpicEditor/commit/4302474e3708fa1d9d0c58dd0d82bdfe08e7978e

It's a little trick I picked up recently. Might be the just the secret sauce we need.

**Comment by OscarGodson** [comment]
Will try it out today! Thanks @Gankro. I'll cherry-pick your commit over and push if it does.

**Comment by OscarGodson** [comment]
Maybe because Firefox upgraded or something, but I cannot repro this anymore. I've tried a repeatedly. I'm just going to close this for now.

**Comment by Gankra** [comment]
Stupid Heisenbugs.
