### ISSUE TITLE
Firefox: texarea does not load until the page is refreshed

### ISSUE THREAD

**Issue by AJ-Acevedo** [OscarGodson/EpicEditor#280]
Any ideas why the text area does not load in Firefox until the page is manually refreshed with a Rails app? It works just fine in Chrome and Safari.

Firefox 23
Rails 4.0.0

When I Inspect Element, the Net tab shows that the css files are not loading until the page gets refreshed.

Here's a screen shot:
![epiceditor-bug](https://f.cloud.github.com/assets/953092/960433/11ffea2c-04b7-11e3-8af8-aa811ad1eae7.png)

**Comment by OscarGodson** [comment]
Does the same JS code work outside of rails?

**Comment by AJ-Acevedo** [comment]
Yup just tested it using the the HTML 5 boiler plate and Firefox 18 and Firefox 23. Worked just fine.

**Comment by OscarGodson** [comment]
Huh, I don't really do any Rails stuff, but could it be that the file just isn't loading? If you're using an asset pipeline, is it in the compiled JS? Does `EpicEditor.version` work if you type it in the console? If `EpicEditor.version` works, is it just that the CSS isn't loading and there's actually a white box you can type into?

**Comment by AJ-Acevedo** [comment]
Strange thing is it works fine in Safari and Chrome. And when you refresh in Firefox it works fine. I'm going to attribute this issue to a Rails asset pipeline or caching issue as the server logs show that on refresh (when it works) the assets are all loaded again and not from cache. I'm going to extract EpicEditor from my project into a Rails gem and get it working right with the asset pipeline. You have an awesome project. Looking forward to contribute back to the project.

**Comment by OscarGodson** [comment]
I believe someone actually made a gem. Might be out of date tho. And yes, all contributions welcome :)

**Comment by OscarGodson** [comment]
Actually, yeah, looks like it was a rails-epiceditor and it's mega out of date.

Added your version here: https://github.com/OscarGodson/EpicEditor/wiki/EpicEditor-Implementations
