### ISSUE TITLE
Specify editor contents programmatically

### ISSUE THREAD

**Issue by svenjacobs** [OscarGodson/EpicEditor#285]
I'm using EpicEditor in a GWT project that is based on the [GWT Platform](https://github.com/ArcBees/GWTP) (GWTP) framework. In GWTP components of a page (called presenters) are singletons and only instantiated once.

That means that EpicEditor on my edit page is also only instantiated once. Now the problem is when the edit page had been previously opened to edit article _A_ and later is revisited to create new article _B_, the previous contents of _A_ is shown in the editor. Unfortunately the contents of the `textarea` is not synced to the editor when changed (sync direction is only editor -> `textarea` and not the other direction). I've tried to `unload()` and `load()` the editor when revisiting my edit page but that didn't help.

I think there are two solutions to this problem:
- Either introduce a bilateral sync between editor and `textarea` so that changes to `textarea` are reflected in editor
- or introduce a `setContents()` method that changes the editor's contents (and of course also syncs to the `textarea`)

**Comment by svenjacobs** [comment]
In addition to the suggested solutions above I believe `load()` should also update the editor's contents based on the `textarea` that has been specified previously in the constructor of EpicEditor.

**Comment by OscarGodson** [comment]
Does `importFile()` not work? If not, why?

**Comment by OscarGodson** [comment]
Just asking because importFile sets the contents and opens a new file which _should_ sync the textarea. The tests are passing and this should catch that: https://github.com/OscarGodson/EpicEditor/blob/develop/test/test.options.js#L255-L263

**Comment by svenjacobs** [comment]
I'm not using client-side storage. Actually I have it explicitly disabled in the constructor with `clientSideStorage: false`. Will it still work?

**Comment by OscarGodson** [comment]
If localStorage is off it just wont save between page loads. All methods work with localStorage off and instead write to an object in memory.

**Comment by svenjacobs** [comment]
I'm sorry for the confusion but it seems the issue is another strange behavior not related to EpicEditor. Closing issue.

**Comment by svenjacobs** [comment]
Still trying to find a fix for my problem. The "strange behavior" I was referring to in my previous comment actually was EpicEditor. EpicEditor will restore the previous contents in `load()` and also sync it to the `textarea`.

Pseudo code:

```
textarea.setText(articleContents); // set new article contents
epicEditor.load(); // restores previous contents overwriting textarea :-(
```

When I add `epicEditor.importFile('article', articleContents);` after `epicEditor.load()` then changes are suddenly not synced to the `textarea` anymore?!

**Comment by OscarGodson** [comment]
If localStorage is turned off there's no way that it could be stored on my side. Are you using Firefox? I know it saves form data between refreshes. Is it possible Firefox is just saving your form data? If that's the issue there's really no way for me to know if the content in there is cached from before by the browser or if it's something you put in with JS. 

As for the 2nd issue. The bug appears to be if you change the file, the textarea is only looking for changes to the original file, not the new one. This does appear to be a bug and i'll look into it and make a new ticket in a bit.

**Comment by OscarGodson** [comment]
OK, fix for this incoming :) just need to write a test or two.

**Comment by svenjacobs** [comment]
I'm using Chrome. Although I use `clientSideStorage: false` I still have the impression that EpicEditor is caching contents because when I perform

``` javascript
var files = editor.getFiles(),
    f;

for (f in files) {
    editor.remove(f);
}
```

when my edit page is hidden then my problem is gone when the edit page is reopened. But this feels a bit _hacky_.

I think there should be an option to completely disable EpicEditor's local caching for situations like mine where only one editor instance can be used for multiple contents.

**Comment by OscarGodson** [comment]
Why do you need to remove all those files and not just opening new files or setting the files back to empty again if you need the same file name? I made EpicEditor with the idea there would be only one instance for 1 page apps. Completely turning off writing to an object would take quite a bit of work since EpicEditor was made with the concept of 1 editor, multiple files, not just a box you type into like a textarea. Maybe you could explain your use case for this better and why you can't just open a new file or reset the file to `''` wont work?

**Comment by OscarGodson** [comment]
In pseudo code, and assuming you only can/want to use 1 file name:

``` js
function eraseFile () {
  app.editor.importFile('article', '');
}

someBtn.addEventListener('click', function () {
  eraseFile();
  app.editor.focus();
});

```

**Comment by svenjacobs** [comment]
I guess if I use a different file for each article and don't rely on the synchronisation with a `textarea` but use `exportFile()` to receive the file's plain text this should work. If not I will let you know :)

**Comment by OscarGodson** [comment]
I should have the textarea sync thing fixed soon. Maybe not tonight. I've run into a few snags, but should be fixed by this weekend for sure!

**Comment by OscarGodson** [comment]
@svenjacobs #286 is closed now. It's working for me and I had written a failing test case. Could you please try it now by pulling develop?
