### ISSUE TITLE
Changing a file with textarea syncing stops syncing

### ISSUE THREAD

**Issue by OscarGodson** [OscarGodson/EpicEditor#286]
For example:

``` html
<body>
  <textarea id="foo"></textarea>
  <div id="epiceditor"></div>
<script>
  var editor = new EpicEditor({ textarea: 'foo', clientSideStorage: false }).load();
  editor.importFile('TEST', 'lol');
</script>
```

The editor will stop syncing now. Problem is we cache the `self.settings.file.name` var outside the `_syncTextarea` function so it will only write to that file which isn't changing.

Reported originally from: #285

**Comment by OscarGodson** [comment]
##RELEASE NOTE: 

This changes the behavior of the `create` event. See b7ca05b's commit message.

**Comment by svenjacobs** [comment]
Yes, I can confirm this has been fixed. Thank you!
