### ISSUE TITLE
Using with textarea: When calling unload() the content is emptied

### ISSUE THREAD

**Issue by SchumacherFM** [OscarGodson/EpicEditor#289]
When unloading the editor the textarea field will be set empty. Why?

https://github.com/OscarGodson/EpicEditor/blob/develop/src/editor.js#L1248

There are many reasons to continue work with the textarea content ...

Thanks in advance for fixing ... e.g. removing that line of code :-)

**Comment by OscarGodson** [comment]
Ha, good point. I'll remove it.

**Comment by OscarGodson** [comment]
OK, remove it, added tests, and checked in Firefox and Chrome. Can you make sure it works as you expect?

**Comment by SchumacherFM** [comment]
Thanks! Works as expected :+1:
