### ISSUE TITLE
Synchronized scrolling in fullscreen mode

### ISSUE THREAD

**Issue by SchumacherFM** [OscarGodson/EpicEditor#290]
Feature: Synchronized scrolling in fullscreen mode like http://dillinger.io/

**Comment by OscarGodson** [comment]
I feel like this has been reported but couldnt find any tickets. Good idea thanks. Dillinger's scrolling on the right is pretty jumpy tho and not smooth. Hopefully theres a way to do it smoother.

**Comment by mpxc8102** [comment]
A really well-done implementation of this feature can be found [here](http://benweet.github.io/stackedit/#). +1 for synchronized scrolling

**Comment by OscarGodson** [comment]
Hmm, ill have to check on desktop. Doesnt scroll (either side) on my phone

**Comment by anaptfox** [comment]
:+1:
