### ISSUE TITLE
Not all markdown works within a table

### ISSUE THREAD

**Issue by TheColorRed** [OscarGodson/EpicEditor#298]
Some of the markdown breaks when it is within a table, here is a screenshot:

![tableerr](https://f.cloud.github.com/assets/1571806/1339911/0ae352a0-3618-11e3-8fde-80653f347925.png)

**Comment by OscarGodson** [comment]
Does it work on GitHub?

**Comment by TheColorRed** [comment]
Nope....

**Comment by OscarGodson** [comment]
We use @chjj's https://github.com/chjj/marked for a default parser and he copies GitHub's Markdown parser. If you think what you put in the table should work you should post in his repo and maybe he will add this functionality. However, EpicEditor doesn't actually have a parser, we just use his.

**Comment by TheColorRed** [comment]
Oh, okay. I thought you wrote the parser.
