### ISSUE TITLE
Allow custom .save() routes and other things

### ISSUE THREAD

**Issue by OscarGodson** [OscarGodson/EpicEditor#30]
The `.save()` method should be configurable  in `.options()` with custom API routes so that `.save()` doesn't only save to localStorage but also some external API.

Something like...

``` javascript
ee.options({
  routes:{
      create:'/api/create/', //on ...?
      read:'/api/read/',     //on .open()
      update:'/api/update/', //on .save()
      remove:'/api/delete/'  //on .remove()
    },
    saving:{
      saveInterval:500,
      saveOnKeyUp:false
    }
  }
}).load();
```

Above sets up 4 custom routes for all your CRUD commands. It also turns off the default saving on keyup and turns on saveInterval which will automatically `.save()` every half a second while focused on the editor. Each half second EE will emit a `'save'` event for you to hook into.

Also, `.save()` will need to accept a callback if create/update is set.

Not entirely sure how the create route would work and read would basically run on `.open()` and remove on `.remove()`. All would have callbacks like `.save()`.

**NOTE:** the D in CRUD stands for delete, but delete is a reserved word in JS. Rather than making users remember to quote `'delete'`, we should use `remove` instead.

cc: @techwraith

**Comment by techwraith** [comment]
So, this will take a little more work, but my preference would be to have the save method use local storage until the create method or read method is used. Basically, I want to be able to store my drafts in local storage before "publishing" my post.

**Comment by OscarGodson** [comment]
@Techwraith I'll think about how/if i'd implement that natively. #31 relates to this. I could have it accept a function and in that function you could do something such as `.on('create',function(){ localStorage['epiceditor'].clear() })`. I'd have to implement a "status" for each file and this is just an editor so nothing is technically a draft, it's just the current state of the file.

Any ideas on how it'd be implemented natively?

If it's not implemented it'd still be easy. You could simply clear the LS in the callback in your form submit.

**Comment by OscarGodson** [comment]
Some more thinking... this might be a great use case for a EE plugin. The plugin would enable draft and published and clear the cache once a file was published.

**Comment by techwraith** [comment]
I think the best way to handle this is to have the editor emit events for each action. Each callback would be passed the page data.

```
ee.on('read', function(page){ // write some logic to send ajax if already published});
ee.on('create', function(page){ // do nothing});
ee.on('remove', function(page){ // write some logic to send ajax if already published});
ee.on('update', function(page){ // write some logic to send ajax if already published});
```

That way you don't even have to worry about the config options, the user can just worry about that themselves. I think this fits better into your vision for this editor.

**Comment by johnmdonahue** [comment]
Just wanted to throw out a few ideas on the file storage, thinking out loud:
1. Would it make sense to provide a method to fetch any or all file objects in a given namespace without loading them. A user could throw them into a dropdown for easy jumping between files:

``` javascript
EpicEditor.prototype.files(namespace, file) { // or .listFiles
  return fileInNameSpace || allFilesInNamespace;
}
```
1. As mentioned, it would be awesome to build with plugins in mind. Save/sync to Dropbox or GitHub for instance would be incredible.
2. For extensibility, it might be useful to add file types to names (i.e. `example-1.md`) and metadata to the file object similar to standard system metadata. for example:

``` javascript
var f = ee.files('epic-editor', 'example-1')
f.status.created // timestamp
f.status.modified // timestamp of last save
```

This could come in handy in an instance where someone has the file open in 2 tabs simultaneously and the modified stamp could be used to handle conflicts.

Not sure the best way to handle the API for this but I wanted to throw it out there for discussion.

Thanks.

**Comment by OscarGodson** [comment]
The finalized API will be what @Techwraith suggested. I'm working on it now.

I made a ticket for @johnmdonahue first suggestion (#85) and 2nd awhile ago (#33) and made a ticket for the 3rd as well (#86)

**Comment by OscarGodson** [comment]
YAY! in our 0.1.0 branch.
