### ISSUE TITLE
EpicEditor in Codeigniter

### ISSUE THREAD

**Issue by bcrute** [OscarGodson/EpicEditor#300]
So I've been playing with this for 3 days now, posted on SO and no luck.  I've been trying to implement epiceditor in codeigniter; the preview buttons change the colors and go fullscreen as normal, but the previews do not convert anything so it looks like what I just typed rather than bold or italic.

I've read through the epiceditor page I don't know how many times, checked the source code and the sources and I've found nothing that I haven't done.  All I can think of right now is that I didn't properly include the parser, but the documentation states that epiceditor automatically includes it, so I'm lost.

**Comment by OscarGodson** [comment]
How did you install it (download the zip, clone the repo, using some 3rd party plugin, etc) and what version of EpicEditor are you using?

If you install the zip it should just work if you use the minified or not minified one. If you try to use /src/editor.js that wont work since it needs to be built. If you're using a custom parser, did you see the docs on that?

Can you reproduce with your same JS in like JSBin? If thats too hard, could you pate the code you used to setup EpicEditor?

**Comment by bcrute** [comment]
I downloaded the zip(0.2.2) from your website, gave the basepath to the themes, and tried using both minified and non-minified code.  I was under the impression that by doing nothing other than set up epiceditor, the 'marked' parser would be included and used.  If that is wrong, please tell me how to include the parser.  I haven't been able to find documentation on this outside of your 4 steps.

```
 require(['epiceditor'], function() {
        var opts = {
            basePath: '/css/epiceditor',
            parser: 'marked',
            autogrow: true
        }
        var editor = new EpicEditor(opts).load();
    });
```

**Comment by OscarGodson** [comment]
The parser should be included. I just downloaded the zip (0.2.2) and `Marked` (the parser) is there. Do you think it's something to do with RequireJS? I've never really used require before. Does typing `marked` into your console return a function definition? If you include the epiceditor.js file (minified or not) marked should exist. I don't know how require works, but do you need to add marked there?

**Comment by OscarGodson** [comment]
Does this help? https://github.com/OscarGodson/EpicEditor/wiki/EpicEditor-with-Module-Loaders

**Comment by bcrute** [comment]
Typing marked into the console returns an undefined error, so it seems like your link may be exactly what I need.  I will try that out and get back to you.  Thank you very much.

**Comment by bcrute** [comment]
Could not get it working with that link, so I just added this to line 2890 of epiceditor.js

```
window.marked = marked;
```

Thanks for your help, though :)

**Comment by OscarGodson** [comment]
I'd be interested in why "this.marked" doesnt work in your case. What is "this" at the very bottom where marked attaches itself to the window?
