### ISSUE TITLE
EpicEditor with CakePHP

### ISSUE THREAD

**Issue by thundeyy** [OscarGodson/EpicEditor#302]
Please, any help on how to use EpicEditor with cakephp..

Thanks in anticipation :-)

**Comment by OscarGodson** [comment]
I really have no idea :\ I haven't done PHP work in years and haven't ever touched CakePHP. My assumption would be... like any other script? How do you include images, stylesheets and js files in Cake? Install is the same. Have you tried asking this on StackOverflow too?
