### ISSUE TITLE
Editor doesn't work with a custom setup in Firefox/IE but does in Chrome

### ISSUE THREAD

**Issue by ghost** [OscarGodson/EpicEditor#304]
I got "too much recursion" errors on Firefox (via Firebug) when I load EpicEditor with those settings

```
var opts = {
    container: 'epiceditor',
    textarea: content,
    basePath: 'static/js/epiceditor',
    clientSideStorage: true,
    localStorageName: 'epiceditor',
    useNativeFullscreen: true,
    parser: marked,
    file: {
        name:'epiceditor',
        defaultContent: '',
        autoSave: 100
    },
    theme: {
        base: '/themes/base/epiceditor.css',
        preview: '/themes/preview/preview-dark.css',
        editor: '/themes/editor/epic-dark.css'
    },
    button: {
        preview: false,
        fullscreen: false,
        bar: "auto"
    },
    focusOnLoad: false,
    autogrow: {
        minHeight: 150,
        maxHeight: 450,
    }
}

var editor = new EpicEditor(opts).load();
```

The only thing I do is updating a hidden textarea with the exported data from the editor via a function like this one :

```
editor.on('update', function () {
    document.getElementById('content').value = editor.exportFile();
}).emit('update');
```

This is for saving data to a db, for later use in a webapp.

Is there something wrong with this ? If there is, why does it work on chrome ?

What did I miss ?

**Comment by OscarGodson** [comment]
I can look more into this, but there's a few weird things here:
1. You're setting the value of the `textarea` to the value that should already be there. Based on your options above, `content` is set as the `textarea` to sync, then, whenever there's a change you re-update the `textarea` to update it again.
2. I'm unable to reproduce with your exact settings _except_ the path to the themes, but that should have no effect on this.

![](https://www.monosnap.com/image/E88SN4RhnzJNA4TjfMiPhmkftREELJ.png)

Could you give a stacktrace of the start/end of the infinite loop Firefox is giving? Not the entire infinite loop, just the piece that keeps looping.

Here's the full bit of code I'm using to try to reproduce:

``` html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>EpicEditor Test</title>
</head>
<body>

  <div id="epiceditor"></div>
  <textarea id="content"></textarea>
  <script src="http://rawgithub.com/OscarGodson/EpicEditor/develop/epiceditor/js/epiceditor.js"></script>
  <script>
    var content = document.getElementById('content'); 
    var opts = {
    container: 'epiceditor',
    textarea: content,
    basePath: 'static/js/epiceditor',
    clientSideStorage: true,
    localStorageName: 'epiceditor',
    useNativeFullscreen: true,
    parser: marked,
    file: {
        name:'epiceditor',
        defaultContent: '',
        autoSave: 100
    },
    theme: {
        base: 'http://rawgithub.com/OscarGodson/EpicEditor/develop/epiceditor/themes/base/epiceditor.css',
        preview: 'http://rawgithub.com/OscarGodson/EpicEditor/develop/epiceditor/themes/preview/preview-dark.css',
        editor: 'http://rawgithub.com/OscarGodson/EpicEditor/develop/epiceditor/themes/editor/epic-dark.css'
    },
    button: {
        preview: false,
        fullscreen: false,
        bar: "auto"
    },
    focusOnLoad: false,
    autogrow: {
        minHeight: 150,
        maxHeight: 450,
    }
}

var editor = new EpicEditor(opts).load();

editor.on('update', function () {
    document.getElementById('content').value = editor.exportFile();
}).emit('update');
  </script>
</body>
</html>
```

**Comment by ghost** [comment]
Ok for the textarea sync, i thought (i don't know why, it's in the doc) that you initialized the editor with it and that was all. My bad.

But then... that's where I should have been more focused : 

```
textarea: content,
```

I used it without quotes, so it waits for an element but... I didn't get the element first like you did with : 

```
var content = document.getElementById('content'); 
```

And directly wrote, without quotes : 

```
textarea: content,
```

So it loops on firefox but not on Chrome. If i put quotes on that string or get the element directly it works, of course.

Gosh, It seems I was coding far too late, how could I miss that ^^'

Bonus "The code that made browsers loop" : 

```
<div id="epiceditor"></div>
<textarea id="content"></textarea>
<script src="http://rawgithub.com/OscarGodson/EpicEditor/develop/epiceditor/js/epiceditor.js"></script>
<script>
var opts = {
    container: 'epiceditor',
    textarea: content,
    basePath: 'static/js/epiceditor',
    clientSideStorage: true,
    localStorageName: 'epiceditor',
    useNativeFullscreen: true,
    parser: marked,
    file: {
        name:'epiceditor',
        defaultContent: '',
        autoSave: 100
    },
    theme: {
        base: 'http://rawgithub.com/OscarGodson/EpicEditor/develop/epiceditor/themes/base/epiceditor.css',
        preview: 'http://rawgithub.com/OscarGodson/EpicEditor/develop/epiceditor/themes/preview/preview-dark.css',
        editor: 'http://rawgithub.com/OscarGodson/EpicEditor/develop/epiceditor/themes/editor/epic-dark.css'
    },
    button: {
        preview: false,
        fullscreen: false,
        bar: "auto"
    },
    focusOnLoad: false,
    autogrow: {
        minHeight: 150,
        maxHeight: 450,
    }
}

var editor = new EpicEditor(opts).load();
```

  </script>

Though getting the element with an id not in a string works on Firefox too, as `document.getElementById(content)` gives the same element as `document.getElementById('content')` in Firefox, Chrome, Opera and IE as far I could test. 

Now, I think we can call this a closed issue. Sorry for the inconvenience and thank you for being so quick to respond, you guided me straight to my mistake !

**Comment by OscarGodson** [comment]
:thumbsup:

**Comment by OscarGodson** [comment]
> Ok for the textarea sync, i thought (i don't know why, it's in the doc)

The docs for the options should say null for the textarea everywhere. I couldn't find the `content` thing you mention. I'd like to fix that tho wherever you found it. could you point me to it?

**Comment by ghost** [comment]
I wasn't clear.

No 'content' anywhere in the doc, that `textarea: content,` was my code. Except I didn't get the element first with a `document.getElementById`.

What I meant was that the doc does clearly say that epiceditor will sync with the textarea related to the ID or object given. And by default, the doc DOES say `textarea: null,`.
