### ISSUE TITLE
Tab key

### ISSUE THREAD

**Issue by nojaf** [OscarGodson/EpicEditor#305]
When I tab in the epic editor I want to add four spaces instead leaving the editor.
Could come in handy when you are writing a code blok.

If you could point me in a direction where I could tried to implement the feature myself I'll do a fork.Thanks!

**Comment by OscarGodson** [comment]
@hongymagic hacked something up here: https://github.com/OscarGodson/EpicEditor/issues/159

There's a link to his commit in the PR description. I'm closing the ticket tho since there's a few tickets about adding tab key support :)
