### ISSUE TITLE
Using Custom code editor

### ISSUE THREAD

**Issue by glassresistor** [OscarGodson/EpicEditor#313]
Trying to workout the best way to using a different code editor than a baseline text box for right side.  Is there a good way to do this?
Would forking and adding this as a config option be worth while?

**Comment by OscarGodson** [comment]
So you mean swapping out the whole editor: editor iframe, parser, etc and just keeping the previewer? If so, what's the benefit exactly? 

I'm open to it, but like 80% of EpicEditor is the editor so I'm not sure why you would exactly :)

**Comment by glassresistor** [comment]
Because things like markitup and code mirror are more user friendly.  A
base text editor isn't as isle to beginners.  Offer highlighting and
plugins.

**Comment by glassresistor** [comment]
Not the parser just text area

**Comment by OscarGodson** [comment]
I guess my question is, what about EpicEditor do you want to use if you want to replace the editor? The parser is just an included module (Marked) and the preview is literally just the HTML dumped into a `div`. My suggestion would be more:
1. The best, obviously, is rather that going through the trouble having EpicEditor support any editor out there (which will be tough) build the features you want into EpicEditor. It could be the same amount of time depending on what you want to do. You just mention "plugins" which is kinda vague, so I'm not sure.
2. Not as ideal from this project's standpoint, but build the features you like in EpicEditor into the editor you prefer.
3. Do what you originally suggest. I wont deny it, but it does seem like out of these two options this would actually be the hardest. You're replacing the major component of EpicEditor and the editor you want to use (CodeMirror, whatever) just to have the smaller features of EpicEditor. 

Again, out of those 3, if you're going to go through the work of doing the 3rd thing and forking the project, etc, it'd be best for all EpicEditor users if you actually built the features you wanted into EpicEditor.

**Comment by glassresistor** [comment]
So what i think is really good about epiceditor is the UI for switching between preview and edit and the fullscreen split screen.  Also localstorage and the api around it also nice usage of marked and ability to swap parser.
The actual area for editing code is no where near as complete as say Ace Editor as shown here in a browserify example with markdown:
http://thlorenz.github.io/browserify-markdown-editor/
Also codemirror
http://codemirror.net/demo/variableheight.html
Both have large communities around them and lots of code with 100s of contributors.  These editors have code completion smart indent vim and emacs mode etc.  Adding this functionality to epiceditor would be a large task but swapping in any of these(all bind to textarea) is very little code.
Epiceditor although not just a textarea is the editor equivalent of notepad(fine but not amazing).  I don't think just switching to either editor is great either because both are still pretty much designed for coders although are still much more usable by non-coders than notepad.
MarkItUp is an editor designer for people used to Word or something and spit out good markdown
http://markitup.jaysalvat.com/examples/markdown/
Being able to swap out editors means that I can use an editor best suited for the desired audience while still not having to use a wysiwyg.

**Comment by OscarGodson** [comment]
> Adding this functionality to epiceditor would be a large task but swapping in any of these(all bind to textarea) is very little code.

If you want to dive in and provide an easy API for it like how easy switching out the parser is, go for it! I don't think it's going to be as easy as you think tho, but try it :) EpicEditor has a bunch of APIs that hook into events and stuff and I think you're going to have an incredibly tough time getting the events correct across any editor, or exporting or importing with the different file types, etc. Luckily theres quite a few tests around these things so you can make sure your editor is passing all those tests.

As long as your implementation is easy to use and isnt a massive chunk of code I'll accept it. I do, however, think that it would be easier just use some localStorage plugin or full screen plugin for those editors than doing this :)

One last thing, your examples you sent are _very_ code editor specific or lacking features you're wanting. If your audience isn't very tech savvy and thats why you want to use one of those I'd be careful about using one of those off the shelf. For example, your first one, it has line folding, line numbers, etc but is missing things that make an easy to use MD editor like buttons or inline formatting (like Mou or Byword, or your CodeMirror example). This is great for people who use, say, Sublime or something but a user is going to find all that clutter confusing and specifically why I went minimalist for EpicEditor. If you _do_ use one of these, I'd suggest CodeMirror and suggest getting rid of as much of that UI chrome as possible. 

MarkItUp on the other hand has buttons, but is missing nearly every feature a decent editor would have that we also don't have (but want to build) like pressing enter to auto create new list items, tabbing, etc. It's basically a less featured, larger, EpicEditor, but it has buttons. I'm not sure what you'd be gaining with it aside form buttons which would be just as hard, if not easier, than integrating this.

**Comment by glassresistor** [comment]
Thanks I'm not planning on using of them for long mostly working on some prototypes write now.  Im definetly interested in taking something like my CodeMirror example and adding buttons.
Improving EpicEditors editor might be a way to do this, I'm not sure yet.  I'll probably see about taking making something ike epiceditor with just a text area.  I am curious as to why epic editor doesn't use a textarea given that the CSS it uses doesn't do much besides color styling(something doable with css)?

**Comment by glassresistor** [comment]
Ended up building the prototype like so:
http://glassresistor.github.io/demo-markdown-editor/
Its pretty ugly code but i think ill just make an epicpreviewer and embed different ones.  Most editors will need hacking on to work and markItUp is really crusty.
