### ISSUE TITLE
Fullscreen in non-supported browsers

### ISSUE THREAD

**Issue by OscarGodson** [OscarGodson/EpicEditor#32]
While not entirely important, it'd be great to still support fullscreen by doing "fullwindow" rather true fullscreen. i.e. the editor would fill the window and act just as if it would in fullscreen in supported browsers.

**Comment by OscarGodson** [comment]
This now doesn't only include IE, but Firefox too see #22 which means this is being bumped to the public alpha milestone

**Comment by OscarGodson** [comment]
Also we'll wanna see if we can trigger IE's fullscreen programmaticall. Users can access fullscreen via <kbd>F11</kbd>, so if possible we'd do the same thing we'd do for other browsers like Firefox by making the `<iframe>` 100% width and height of the window, but then trigger <kbd>F11</kbd>, if possible. If not we should probably show a note to IE users that they can make it more fullscreen by pressing <kbd>F11</kbd>

Also, we'll wanna block the ability to scroll the window while in fullscreen and hide the window scrollbars

**Comment by OscarGodson** [comment]
Making progress:

**Firefox**:  
![firefox fullscreen](https://img.skitch.com/20120311-x9u3pp4y57enh2agfbd97knxk5.png)

It's pretty buggy right now unfortunately. There's still some kinks I wanna work out before pushing anything to our 0.1.0 branch, but in case anyone is following this, it's getting close.

**Comment by dadambickford** [comment]
Looking good! I was just testing out that new pull request from @jwmcpeak and wanted to make sure you were aware of whats goin on with the fullscreen in safari. It's supported but has a big wonky white bar in the center, and wouldn't let me input any text.

**Comment by OscarGodson** [comment]
@dadambickford yep, it's on the list, see: #6

I had assigned it to you awhile ago since I figure it's more of a CSS issue in the JS where I setup all the styles for fullscreen. The 0.1.0 branch has fullscreen working now (but you can't close fullscreen yet! Have to refresh) if you wanna take a stab at getting it to work right go ahead. It's assigned to you so I wont touch it unless you assign it back to me.

**Comment by OscarGodson** [comment]
Working in FF and Chrome now. IE9 is the last one and we can finally close this sucker!

**Comment by OscarGodson** [comment]
Well, this was strange. EpicEditor is working great out of the box in IE9 now.
