### ISSUE TITLE
autogrow on startup

### ISSUE THREAD

**Issue by fokoenecke** [OscarGodson/EpicEditor#324]
I am using EpicEditor in a bootstrap environment. I use multiple editors on one page. The HTML is getting generated by the templating engine mako. Code looks like this:

``` html
<div class="project-description form-group">
    <label class="form-control">Beschreibung
        <div class="project-description-editor form-control"></div>
    </label>
    <textarea class="no-display">${project.description}</textarea>
</div>
```

When the editors are loaded, their size does not match their according container elements, although I specify _autogrow = true_ in my options. If I use the editor by typing or clicking on preview, the size instantly changes to my expected outcome. Same thing does **not** work if I call those functions from javascript nor if I call _reflow()_. My code for loading the editors looks like this:

``` javascript
$description_editors = $area.find('.project-description-editor');
$.each($description_editors, function( index, editor ) {
    var textarea = $(editor).closest('.project-description').find('textarea').get(0);
    var opts = {
        container: editor,
        textarea: textarea,
        clientSideStorage: false,
        useNativeFullscreen: true,
        parser: marked,
        theme: {
            base: '/fanstatic/mindboard/css/epiceditor.css',
            preview: '/fanstatic/mindboard/css/github.css',
            editor: '/fanstatic/mindboard/css/epic-light.css'
        },
        button: {
            preview: true,
            fullscreen: false,
            bar: "auto"
        },
        autogrow: true,
    };

    var editor = new EpicEditor(opts).load().on('update', function () {
        $project = $(this.getElement('container')).closest('li');
        update_project($project);
    });
});
```

ps. auto-integrating the textarea did not work for me, but I didn't try that hard ;)

**Comment by massar** [comment]
autogrow does not work when related CSS is stopping the elements from resizing. Hence check your CSS.
