### ISSUE TITLE
Side by side editing when not in fullscreen mode

### ISSUE THREAD

**Issue by giodamelio** [OscarGodson/EpicEditor#337]
I want to be able to preview in real time like I am in fullscreen mode. Is there any way to do that?

**Comment by ghost** [comment]
You can do like this in the html : 

```
<div id="epiceditor-preview"></div>
```

And in the js script where you initialize epiceditor, add this with the correct id you just defined : 

```
var editor = new EpicEditor(opts);
editor.load();

editor.on('update', function () {
    document.querySelector('#epiceditor-preview').innerHTML = this.exportFile(null, 'html');
}).emit('update');
```

Something like that. Putting those things side by side is just css after that.

**Comment by giodamelio** [comment]
Awesome, thanks
