### ISSUE TITLE
when it will be possible to open in epiceditor files from local file system

### ISSUE THREAD

**Issue by derberg** [OscarGodson/EpicEditor#338]
So you api allows to do awesome things, like open a file or save a file or rename it, but only within defined local storage. Each api method states the following note:

```
Note: This does not open files on your server or machine (yet). This simply looks in localStorage where EpicEditor stores drafts.
```

so the question is, when it will be possible to really open in epiceditor a file from local file system?

**Comment by massar** [comment]
Storing a file on the local machine can be done by serving it to the user as text/plain, loading it would need a little upload form.
