### ISSUE TITLE
No fullscreen in Chrome

### ISSUE THREAD

**Issue by ghost** [OscarGodson/EpicEditor#342]
Fullscreen was fine in Chrome (Version 37.0.2062.94) and then all of a sudden it wasn't – just a blank white screen. Toggling preview within the window still works fine. This is viewing both my local files and epiceditor's own site.
Fullscreen is ok in Firefox 31.0 on the same system.
Tried simple things like restarting Chrome, clearing cache but no change.
Any ideas?
Many thanks.

**Comment by cionevn** [comment]
I got the same your issues. I will take a look on my the code if let you know if I can figure out what's went wrong ;)

**Comment by zethussuen** [comment]
@luckystairs I know this issue is old, but can you still confirm in current builds of Chrome? I haven't been seeing this issue for a while now.

Version 41.0.2272.118 (64-bit)

**Comment by ghost** [comment]
no sorry – too long ago. my project moved around for all sorts of reasons and epic became not necessary.
D.

**Comment by zethussuen** [comment]
Ok thanks. Closing this issue in favor of #331

**Comment by wy-z** [comment]
I got the same issues.
Chrome 43.0.2357.124 (64-bit)
But it will be ok, once i open the console.
work well in safari. 
![image](https://cloud.githubusercontent.com/assets/4213483/8159218/170ce4c0-1397-11e5-8d78-f1fef7748ab4.png)
![image](https://cloud.githubusercontent.com/assets/4213483/8159235/33d2172e-1397-11e5-8c68-7670831166ea.png)
