### ISSUE TITLE
Question: How to make EpicEditor work with google fonts?

### ISSUE THREAD

**Issue by keevitaja** [OscarGodson/EpicEditor#344]
Hi,

Is it possible to make the Editor work with google fonts?

Thanks!

**Comment by OscarGodson** [comment]
In the theme's CSS just add the font CSS import

**Comment by keevitaja** [comment]
Thanks!

**Comment by keevitaja** [comment]
Hi again. One more question. 

Is it possible to add some content to the editor with jquery?

I have a link and i need to add the url to the editor when users clicks it. From jquery end is not the problem, but i can't find the correct selector for this.

**Comment by OscarGodson** [comment]
You can either do 

```
editor.importFile('some-file',"#Imported markdown\nFancy, huh?");
```

Or if you want direct access to the element to do manipulation:

```
editor.getElement('editor').body.innerHTML
```

**Comment by OscarGodson** [comment]
Obviously you can use jQuery, those are just examples from the docs.
