### ISSUE TITLE
[Feature] {theme:false} = Ignore dynamic CSS 

### ISSUE THREAD

**Issue by ludoo0d0a** [OscarGodson/EpicEditor#345]
If the website used minified CSS, then we don't want to include theme dynamically at the editor loading.

Could you update your code so that theme : false in options won't added any CSS.
Responsibility to the user to add themes CSS himself.

Thanks

**Comment by ludoo0d0a** [comment]
[edit] Since EpicEditor is iframe, a link in theme option for the minified CSS would be just great !

**Comment by OscarGodson** [comment]
You can just set the theme options to empty or null or whatever. So theme.base: '', theme.preview: '', theme.editor: '' already I believe can't you?

**Comment by OscarGodson** [comment]
To your edit, same as above but set it to your css. There's more details in the docs.

**Comment by ludoo0d0a** [comment]
For null options, the issue is that _insertCSSLink will anyway add a tag for the CSS (no check if false/null)

OK, I see now the section about themes.
and I understand that using a single minified for the 3 iframes is not probably the best way to do.
i will think about this.

**Comment by OscarGodson** [comment]
@ludoo0d0a if you're doing caching you could include 3 of the same CSS files and it shouldn't really affect the load time much at all since you, and your browser, are going to be caching it
