### ISSUE TITLE
Preview and editor side by side

### ISSUE THREAD

**Issue by ludoo0d0a** [OscarGodson/EpicEditor#347]
Would it be hard to get an option to display preview and editor side by side (+synced) ?

**Comment by OscarGodson** [comment]
This has a few dupes so im gonna close it. But it shouldn't be hard. I believe something like this would let you do thishttps://gist.github.com/OscarGodson/d58ef4994ee703ce6622

**Comment by ludoo0d0a** [comment]
Great, and clean solution !
