### ISSUE TITLE
What are the "scripts and assets"?

### ISSUE THREAD

**Issue by ethel-dev** [OscarGodson/EpicEditor#350]
I am only getting some text and 4 unlabeled buttons with EpicEditor quickstart? What are the "scripts and assets."
Basically I'm asking what stylesheets and such I should add.

**Comment by OscarGodson** [comment]
If you load up EpicEditor without the assets your console should give you errors about the missing files and that way you can see where its looking for the files. For example:

![index html 2014-12-14 01-36-00](https://cloud.githubusercontent.com/assets/20615/5426952/95aafc8c-8331-11e4-9f3e-f1c8dfd191ae.png)

To get EpicEditor running there's 5 files:
1. Some HTML file that includes all the CSS and JS assets
2. EpicEditor JS file
3. A base CSS file
4. A preview CSS file
5. A editor CSS file

You can set the paths of the CSS files with the `theme` option. By default it looks in the path you see in the image above, but you can set it to whatever you want like:

``` js
var opts = {
  theme: {
    base: '/path/to/my/themes/base/epiceditor.css',
    preview: '/path/to/my/themes/preview/preview-dark.css',
    editor: '/path/to/my/themes/editor/epic-dark.css'
  }
}
var editor = new EpicEditor(opts);
```

**Comment by ethel-dev** [comment]
So what would my `<head>` look like? What scripts and stylesheets would it have?

**Comment by OscarGodson** [comment]
Your head would have nothing. Above the `</body>` tag you'd have the `epiceditor.min.js` file and thats it.

**Comment by OscarGodson** [comment]
It loads the CSS files which you see it trying to load and fail if you load the JS file and the CSS files aren't in the right place.

**Comment by ethel-dev** [comment]
It doesn't do anything, it still does the same thing.

**Comment by OscarGodson** [comment]
"it doesn't do anything" isn't much info. Can you give me a screenshot of your JS console?

**Comment by ethel-dev** [comment]
I fixed it.

**Comment by ethel-dev** [comment]
I needed my container to be empty, but instead I was putting the `<script>` in the container.

**Comment by OscarGodson** [comment]
:+1:
