### ISSUE TITLE
is there an option to Forbidden HTML?

### ISSUE THREAD

**Issue by duguying** [OscarGodson/EpicEditor#352]
is there an option to Forbidden HTML?

**Comment by OscarGodson** [comment]
EpicEditor just takes what the parser gives it back and puts it into the preview. By default we use a markdown parser called Marked, but you can use anything you want by setting the `parser` option. There's info on how to use it here: https://github.com/OscarGodson/EpicEditor#custom-parsers

**Comment by OscarGodson** [comment]
So, in short, there's no built in way because EpicEditor itself doesn't handle the content parsing that way. EpicEditor just passes raw text to the parser and puts the parsed content into the preview.

**Comment by duguying** [comment]
thank you for you help
