### ISSUE TITLE
I cannot figure out how to get epiceditor to work

### ISSUE THREAD

**Issue by tyleisher** [OscarGodson/EpicEditor#354]
Here is the code of my HTML page. The epiceditor.js is in the same directory.

I've also tried loading in a css file but it doesn't do anything but change the background color.

Any ideas what I am doing wrong?

```
<html>
<head>
    <title>Epic Editor Test</title>
  <script src="epiceditor.js"></script>
  <script>var editor = new EpicEditor().load();</script>
</head>
<body>
  <div id="epiceditor"></div>  
</body>
</html>
```

**Comment by OscarGodson** [comment]
In general, for most scripts unless explicitly stated otherwise (like analytics and tracking code), you should put your script at the bottom of your HTML document right above `</body>`. You closed this so I assume you fixed it, but let me know if not.
