### ISSUE TITLE
http://epiceditor.com/ is down

### ISSUE THREAD

**Issue by orf** [OscarGodson/EpicEditor#359]
http://epiceditor.com/ appears to be down, any idea when/if it will be up?

**Comment by elliottregan** [comment]
Still down...

**Comment by OscarGodson** [comment]
Is it still down? I'm closing this issue. Not sure what was up but I checked on a couple different browsers and downforeveryoneorjustme.com and get

> It's just you. http://epiceditor.com is up.

**Comment by d4nyll** [comment]
It was showing up as a GitHub pages error, something to do with DNS settings if I remembered correctly. It is showing up fine now!

**Comment by elliottregan** [comment]
Huh. Maybe it was a temporary thing. Working on my iPhone at the moment.
