### ISSUE TITLE
2px smaller preview in IE9

### ISSUE THREAD

**Issue by OscarGodson** [OscarGodson/EpicEditor#36]
I thought this was fixed with this code:
https://github.com/OscarGodson/EpicEditor/blob/master/epiceditor.js#L343-346

And it's working here when i was testing it:
http://kneedeepincode.com/epiceditor

but on our gh-page its like the `2px` is never getting added. On the kneedeepincode page I added a breakpoint inside the if and checked the height and it was like `329` (right) and then added another breakpoint right outside the if and checked the height again and it was indeed `331`. On the gh-page tho, the 2nd breakpoint is reporting `329`. So... im clueless.

The best fix would be to get rid of that `_isIE()` line and actually figure out wtf is going on exactly.

**Comment by RaymondCrandall** [comment]
If you use points (pt) instead of pixels for the dimensions I'm pretty sure IE doesn't have trouble rendering on that measurement system.

**Comment by OscarGodson** [comment]
Might be a hack. You could do a pull request to test. We for sure want to
keep it for px everywhere else since pt is meant just for print, but if the
hack fixes it we could wrap it in an _isIE() function, or we could figure
out the actual root of the issue. I personally dont care how we hack it to
work for now.

I also don't know if this is still an issue after #59 which is something
else to check whoever tries to tackle this. First make sure it's still
happening, if so, try pt just for IE or figure out the real issue.
