### ISSUE TITLE
saving the markdown input

### ISSUE THREAD

**Issue by ThomasRoest** [OscarGodson/EpicEditor#361]
Hi, 

How can I save the markdown input to the database, along with the generated html?
I need the orignal markdown input as the user generated content is editable. 

thanks

**Comment by OscarGodson** [comment]
There's an example in the docs under `exportFile([filename],[type])`

But to slightly modify it to your use case:

``` js
syncWithServerBtn.onclick = function () {
  var theMarkdown = editor.exportFile();
  var theHtml = editor.exportFile(null, 'html');
  saveToServerAjaxCall('/save', {markdown: theMarkdown, html: theHtml}, function () {
    console.log('Markdown and HTML was saved to the database.');
  });
}
```
