### ISSUE TITLE
init editor error according by the quickstart

### ISSUE THREAD

**Issue by wangchenOS** [OscarGodson/EpicEditor#365]
hi,i am a newbie , now i use the lastest  project js files and init an editor according by  the quickstart 

```
<head>

<script src="epiceditor/js/epiceditor.js"></script>
<script type="text/javascript">
var editor = new EpicEditor().load();
</script>
</head>
<body>
<div id="epiceditor"></div>
</body>
```

but chrome shows nothing and there is an error occured like this:
![image](https://cloud.githubusercontent.com/assets/8773246/7496128/ea7dd4c6-f444-11e4-90f8-6e91f861fd68.png)
what is the problem？

**Comment by OscarGodson** [comment]
That's just JS, not specific to EpicEditor. You need to put the JS at the bottom of the `</body>` so all the HTML is loaded, or, if you need it in the `<head>` you need to wait for the DOM (HTML) to be loaded with 

https://developer.mozilla.org/en-US/docs/Web/Events/DOMContentLoaded
