### ISSUE TITLE
How to change rendering for specific elements

### ISSUE THREAD

**Issue by ckosmowski** [OscarGodson/EpicEditor#368]
I'd like to augment the markdown with some special type of links in my application (linking between objects). I saw that with "Marked" this should be possible by overwriting methods of the renderer. But how can i do this with epic editor? There is no marked.Renderer object to use.

**Comment by mikekoetter** [comment]
agree - I had assumed that since marked.js was the default parser, I would be able replace the default marked renderer

**Comment by OscarGodson** [comment]
There's a section in the README about replacing the parser: https://github.com/OscarGodson/EpicEditor#custom-parsers

**Comment by mikekoetter** [comment]
Replacing the parser doesn't replace the renderer

**Comment by massar** [comment]
The parser is both a Markdown parser and causes things to be rendered.
Hence, when you change the parser, you change what the output is that is generated.
