### ISSUE TITLE
Fullscreen error in chrome

### ISSUE THREAD

**Issue by wy-z** [OscarGodson/EpicEditor#370]
Chrome 43.0.2357.124 (64-bit)
But it will be ok, once i open the console.
work well in safari. 
![image](https://cloud.githubusercontent.com/assets/4213483/8159218/170ce4c0-1397-11e5-8d78-f1fef7748ab4.png)
![image](https://cloud.githubusercontent.com/assets/4213483/8159235/33d2172e-1397-11e5-8c68-7670831166ea.png)

**Comment by weiyoung-zhou** [comment]
commits earlier than 5131d906b69cf4d0ab85bad70dfd52fa6d68ad24 work well.

**Comment by massar** [comment]
Can't replicate, can you please provide more details?

As this was a issue from ~5 months ago, closing; please re-open when provided more details.

**Comment by OscarGodson** [comment]
Don't know if it still happens but this was an issue in Safari and why Safari doesn't use the native full screen thing. I think it's probably still a thing there
