### ISSUE TITLE
Starting template

### ISSUE THREAD

**Issue by amlwwalker** [OscarGodson/EpicEditor#371]
hi
One of the reasons I want to use epiceditor is because I think I will be able to load a template in - so that each time I create a new document, i have a basic document to work from. 
If I am running this locally is there any way to save and load local .md files that you know already exists, I know I would need some server side code but thought you might know of some?

**Comment by massar** [comment]
You would need to add some extra javascript-based functionality to be able to do this.

You can set it in opts->file->defaultContent when you start EpicEditor or push it into the textarea that you define.
