### ISSUE TITLE
Broken Avatars - Footer

### ISSUE THREAD

**Issue by waseem18** [OscarGodson/EpicEditor#378]
In footer the four images are broken.
![not](https://cloud.githubusercontent.com/assets/5843007/11156069/95462960-8a6f-11e5-874d-c6b9971b9c2f.PNG)

Code tries to access avatars from Twitter using `http://twitter.com/api/users/profile_image?screen_name`. But Twitter API doesn't serve this anymore.  So either we need to place avatar url directly in the code or use this way (http://stackoverflow.com/a/17110904/2820154) to get the avatars.

**Comment by OscarGodson** [comment]
They can just be removed embedded, linked from another place, or removed entirely :)
