### ISSUE TITLE
EpicEditor Icon/Logo

### ISSUE THREAD

**Issue by OscarGodson** [OscarGodson/EpicEditor#43]
@sebnitu is working on it, but making a stub to discuss whenever it's finished.

**Comment by sebnitu** [comment]
Here is the first concept I got put together. Let me know what you think :)

![EpicEditor Logo](http://f.cl.ly/items/3h1z0E2q3o0l34302h0q/EpicEditor-branding.jpg)
http://cl.ly/EraP

**Comment by OscarGodson** [comment]
...wow. That's insanely cool. Wasn't sure what to expect, but while writing this message i've opened it 3 times just to see it again :P

I'll use this as is unless you wanted to tweak it anymore? If not I'll work it into the README and index.html docs (unless of course you wanted to for some reason).

I'll make sure to give you proper credit in the docs and some tweets tomorrow too when it's not dead on Twitter.

again, thanks a lot!

**Comment by OscarGodson** [comment]
I'd also love to use one of those yellow textured backgrounds for the docs. In your .ai/.psd could you give me a tile? It's sexy and i think I can work it in haha

**Comment by mxriverlynn** [comment]
<3

**Comment by j-hernandez** [comment]
Logo status: Superdope.

**Comment by sebnitu** [comment]
Sick dude, glad you guys like it :D 

I'd like to play with it just a little more but depends on how soon you need it by. I probably won't get more time to work on it till this weekend so if you need to get this up before then, no worries.

Here are some links to the AI and PSD files. You should be able to grab the texture from the PSD but let me know if you have trouble.

AI: http://cl.ly/ErfN
PSD: http://cl.ly/Erep

Thanks man!

**Comment by OscarGodson** [comment]
@sebnitu Sounds good to me :) I can't really work on EE until the weekend either.

**Comment by johnmdonahue** [comment]
Badass.

**Comment by samhowat** [comment]
I'm stoked to see this editor come together, and I love the logo!

**Comment by OscarGodson** [comment]
I'd like to do what GitHub does with the logo too when you right click. (go ahead, right click on the GitHub logo on the top left).

cc: @sebnitu
