### ISSUE TITLE
Change out saving on keypress to on an interval

### ISSUE THREAD

**Issue by OscarGodson** [OscarGodson/EpicEditor#47]
Add an option for performance if it's an issue, but by default save every `100ms` rather than on keypress. This will also fix issues with copy and pasting using a right click context menu or the file menu and not your keyboard.

Filing as a bug since it's "technically" a bug that it wont save when you copy and paste and nothing shows up.

**Comment by OscarGodson** [comment]
Have this working already locally

**Comment by RaymondCrandall** [comment]
Would you also want to update the previewer at the same time the interval happened, that way you could see it as well? (is it the previewer you would be updating?)

**Comment by OscarGodson** [comment]
The previewer updates in realtime if you want already (see fullscreen mode). To save on CPU, you have to tell EE that you want it to update the previewer "live", but that's already implemented. This one is already finished, but it's not merged into master yet. It's in the 0.1.0 branch tho... i should tag these...

**Comment by RaymondCrandall** [comment]
I noticed you said you already fixed it, so I figured it would be a good exercise while I familiarize myself with the project. I could do something else though.

**Comment by OscarGodson** [comment]
Check out my last commit in 0.1.0. You can look to familiarize if you want :) also feedback on the commit is appreciated too

**Comment by OscarGodson** [comment]
Yeah go ahead and commit in the commit feedback or here :)

On Mar 9, 2012, at 3:53 PM, Raymond Crandall
reply@reply.github.com
wrote:
