### ISSUE TITLE
Full screen button on utilbar doesn't show up in FF3 FF10 IE9 on Win7

### ISSUE THREAD

**Issue by RaymondCrandall** [OscarGodson/EpicEditor#50]
Not sure if FF3 is important now, but I updated to 10 and it had the same problem. I also checked in IE9, and the same problem was happening. Only the button to preview is present, but the fullscreen button is not being rendered properly.

**Comment by OscarGodson** [comment]
I'm hiding it from browsers that don't support it see #32. As for Firefox and why it's not using native fullscreen see #22. Faux fullscreen is the last ticket in the alpha and it's the thing I'm workin on this weekend and it'll close out #32.  I'll keep this open as a reminder to unhide the button after.

**Comment by OscarGodson** [comment]
The button will no longer be hidden in all browsers.

**Note:** this is in the 0.1.0 branch, and not yet in master, but feel free to test out 0.1.0 until it's released which has this fixed.
