### ISSUE TITLE
Fullscreen preview display scrolling issue

### ISSUE THREAD

**Issue by dadambickford** [OscarGodson/EpicEditor#55]
Right now when you copy our README.md into EE, and go to fullscreen display, it doesn't want to let you scroll all the way down the preview half, cutting off quite a bit of the preview. Could be related to the HTML code that is in our md file.

**Comment by OscarGodson** [comment]
Also to note, when trying a large pure MD file it works fine (or so it seems...)

**Comment by OscarGodson** [comment]
This was fixed when I switched EE to Marked (thank god). Our README now works fine
