### ISSUE TITLE
Triple Iframe's Instead of a Single Wrapper One

### ISSUE THREAD

**Issue by OscarGodson** [OscarGodson/EpicEditor#59]
<h3>Overview</h3>

This has been bugging me and it's just something I didn't realize would be such an issue when i began. Also, having talked with the team at work who works on Etherpad I realized some flaws in my original design. The "chrome", editor and the previewer should be different `<iframes>`. This way CSS and JS is separated and will cause less of a chance of breaking.

<h3>The problems</h3>

I noticed when @dadambickford accidentally forgot to add the `.epiceditor-utilbar` styles to the GitHub theme it completely broke fullscreen. I also noticed it's almost impossible to control the scrollbar position accurately as @dadambickford and I both have tried dealing with. Closing fullscreen has become crazy hard because I can't just resize an `<iframe>`, i have to resize and duplicate _all_ the DOM element styles back to be the same again. And there's misc. other issues that would be solved such as:
- #51 
- #48 (we could truly break out EE "chrome", previewer, and editor styles)
- #25 (different iframes, so scroll position wouldn't be lost)
- #13

<h3>The fix</h3>

The fix would require some key changes at the top where we set `this.editor`, `this.previewer`, and `this.iframe`, but after swapping out the values everything _should_ run fine.

We'd have one `<iframe>` that wraps all the others. This keeps EE away from the parent frame (the `window`) and would contain the utilbar and any other chrome we decide to add later on. Next, the editor should be it's own, and the previewer as well. `this.editor` would still reference the `<textarea>`, and the `<div>` for `this.previewer`, but there'd be an extra hidden `<iframe>` layer.

I want to do this fix for `0.1.0` because the fullscreen in all the browsers is showing to be pretty tough to swap back and forth with DOM elements messing with each other.

cc: @johnmdonahue @dadambickford - Please let me know if you see any issues or have concerns with this plan as it's going to change up the core structure completely.

**Comment by dadambickford** [comment]
this was a comment on reddit - "Are the editor and preview DOMs totally separate? Outside of any wrapper? If so, this could be very useful, since it would be flexible enough for me to display the preview section in any way I wanted.
Otherwise if it's bundled together, I don't think I would ever use it in practice."

obviously were not going to build it to cater every single complaint, but it sounds like with this structure we could potentially have flexibility like above. and people implementing it in their apps or websites could display the editor or preview however they wanted.

**Comment by OscarGodson** [comment]
I've made a lot of progress tonight on this. I've added the three iframes, and it looks just like it did before but now you get three CSS files: base, editor, and previewer. The base has the utilbar stuff because it floats above both the editor and previewer, and the editor for example just has:

![editor.css](https://img.skitch.com/20120319-pte2iianp7nee86j5pwp6ud2s.png)

It's awesome! I wish I would have done this from the start. Theming is 100x easier now. Notice how I don't need classes. This _should_ make a lot of these issues above much faster to fix. There's an issue with the `mousemove` event on the wrapping iframe, but once I get that sorted I'll push this up and get back to work on fullscreen.

**Comment by johnmdonahue** [comment]
This sounds like a great idea! I'm all for it. 

What branch are you working on this? It would be awesome if we could work on this change along side the build update.

**Comment by OscarGodson** [comment]
I'm working in 0.1.0 for it, but when I'm done I can cherry pick this
commit into your branch if you want. After this I'm back to
(hopefully) finally finishing fullscreen which should be helped a lot
from this

On Mar 19, 2012, at 10:45 AM, John Donahue
reply@reply.github.com
wrote:

**Comment by OscarGodson** [comment]
Super close to being done. FF (of course FF) is having some issues with the localStorage and reading from the contenteditable `<body>`, but otherwise all 4 of those bugs above are fixed! This is awesome and themes are so much cleaner. Gotta work out the FF bugs and will push this up.

**Comment by johnmdonahue** [comment]
Awesome man. Can't wait to check it out!

**Comment by OscarGodson** [comment]
All 4 of those are now fixed. (WHEE!) There's an issue with the iframe's fullscreen (it's a small issue, but good enough to push). Pull down 0.1.0 and let me know any other bugs other than fullscreen shizzit

cc: @dadambickford @johnmdonahue

**Comment by dadambickford** [comment]
I checked it out, and as far as i can tell, functionality is great. i noticed some weird differences in how the markdown renders in different browsers though, as you can see [here](http://i.imgur.com/XxvVY.jpg) and [here](http://i.imgur.com/gn5BO.jpg). 

couple minor changes I made in 0.1.0, I updated the footer in the index and readme to read that we were now using Marked and to recognize chris jeffery, the creater.

also changed the new `load()` - `unload()` "try it" anchor tag to a button tag, to make it more noticeable. i love this btw, feels exactly like how I think a dropdown editor should feel.

**Comment by OscarGodson** [comment]
Oh god... Firefox looks SUPER bad on mine. Like, terrible. It also takes a full 1-2 seconds to render. It's either Marked or my `_getText` / `_setText` which is a shim for Firefox. Maybe you can mess with it or test it?

Also, the fullscreen issue acting weird i figured out, but now the button doesn't work (see the commented out `//_goFullscreen()`). Balls. Gotta figure that out. Wanna try?

The try it as a is perfect! I wanted to do that. And good job on the copyright stuff in the footer. You should remove the <q>Also, Isaac Z. Schlueter for his port of GitHub Flavored Markdown which I forked.</q> too.

**Comment by OscarGodson** [comment]
Nevermind about the rendering time. Thats because when i copy and pasted I did it from Chrome to Firefox and it copied all the HTML along with it so it was rendering 2 HTML docs at once :)

**Comment by OscarGodson** [comment]
@dadambickford Hey, got fullscreen not borked again. Just had to move my `webkitRequestFullscreen()` call before I asked for the `window` width. There's still a _small_ issue in native fullscreen tho where you can scroll left to right just a little bit and so in some cases words are slightly clipped

![example](https://img.skitch.com/20120321-myxqn6iex64ag1h5h9pq2n55i1.png)

Should be something small. Looks like the `<body>` or `<html>` probably needs to lose their padding or margins during fullscreen. Make sure it works ok in Firefox tho since as of right now fullscreen opens great in Firefox.

**Comment by johnmdonahue** [comment]
```
Mac OSX 10.7.3
- Safari 5.1.4
- Chrome 17.0.963.79

* 58a217d - (HEAD, upstream/0.1.0, 0.1.0) Got webkit fullscreen working again re: #59 (3 hours ago)
* 2b75c12 - Minor stuff for #59 (13 hours ago)
```

I noticed this while working on the build branch prior to the latest commits but am still seeing it. Is anyone else seeing this behavior or am I doing something wrong here? (BTW: No errors in the console)

### After exiting full screen on Chrome:

![](http://f.cl.ly/items/1B1P050z1z032b3n0A1P/Screen%20Shot%202012-03-21%20at%2010.49.11%20AM.png)

### After exiting full screen on Safari

It seems to have a similar problem except that it just loses the buttons on hover, but if inspected will redraw to look like the screenshot above:

![](http://f.cl.ly/items/3N0o0w1R3l0I0D111v17/Screen%20Shot%202012-03-21%20at%2011.04.06%20AM.png)

**Comment by OscarGodson** [comment]
Nope. I was having lots of issues with closing fullscreen. Ive just finally in the last commit gotten fullscreen (for the most part) working again with the new iframe layout stuff.

Im going to try to now get fullscreen to close correctly. I wouldn't have ever gotten in the last iteration with one iframe. It's still using the same closing fullscreen code as I was using before the new iframe stuff, haven't touched closing it yet. :)

**Comment by johnmdonahue** [comment]
Ahh gotcha. Looking great on my end otherwise. Thanks!

**Comment by johnmdonahue** [comment]
Just a heads up, I am seeing the following on full screen in Safari. I haven't had a chance to look into it, just wanted to put it on the radar. Otherwise looking good on my end.

![](http://f.cl.ly/items/3f283K090L0V3l3K0M0H/Screen%20Shot%202012-03-22%20at%2010.46.06%20AM.png)

**Comment by OscarGodson** [comment]
@johnmdonahue yeah, thats an old issue. #6 actually. Me and @dadambickford couldn't figure it out :\
