### ISSUE TITLE
Get fullscreen working correctly in Safari

### ISSUE THREAD

**Issue by OscarGodson** [OscarGodson/EpicEditor#6]
It's pretty buggy right now for some reason:
- Full screen doesn't actually fit fullscreen
- Closing fullscreen has a weird flash of an unstyled editor.

**Comment by dadambickford** [comment]
Also just noticed, in safari, that if you try going to fullscreen, and then revert back. all of the sudden the util bar will not show up, and even the keyboard shortcuts will not change between preview/editor anymore.

**Comment by OscarGodson** [comment]
Yeah, the utilbar and stuff is still broken going back on all browsers. If you can just get it looking ok in fullscreen all the reverting will look fine once im done with it unless you want to take a stab at the reverting of styles.

**Comment by dadambickford** [comment]
alright, yeah i was going to try and get this one knocked out today. we'll see how it goes.

**Comment by OscarGodson** [comment]
Now this happens _after_ i close fullscreen once. To get true fullscreen i have to totally quit Safari and reopen it. WTF?!

![safari is fucked](https://img.skitch.com/20120319-8sdn5f9wiqbap86main49bsrwi.png)

**Comment by OscarGodson** [comment]
I'm going to check for Safari in 0.1.2 and have it use the faux fullscreen since getting real fullscreen to work seems to be too hard.

**Comment by OscarGodson** [comment]
have the nasty fix in there for now. We'll need to open a new ticket if Safari ever gets fixed

**Comment by OscarGodson** [comment]
Tested on Safari 6. Still works like shit... Updated the comment.
