### ISSUE TITLE
Cannot read property 'contentDocument' of null

### ISSUE THREAD

**Issue by davidshen84** [OscarGodson/EpicEditor#71]
```
var ee = new EpicEditor($('<div></div>'));
```

If I ran the above code, I got the 'Cannot read property **"contentDocument"** of null' error. If the element used to initialize the editor is attached to the page document already, this error will not occur. Is it possible to fix this?

**Comment by OscarGodson** [comment]
Looks like you're using jQuery? Above isn't attaching it to the DOM at all and most likely why it's freaking out. You're trying to do a bunch of crazy stuff in memory including modifying `<iframe>`s which probably has security issues too.

You need to actually append that DOM fragment that's in memory and then give EE a reference to that DOM element. I believe this should work (although I haven't tested this)

``` javascript
$('<div></div>').attr('id','foo').appendTo('body');
var el = $('#foo').get(0);
var ee = new EpicEditor(el);
```

Let me know if that does or doesn't work.

**Comment by davidshen84** [comment]
Sure, I know the above code would work. I just want to know if putting everything in the memory before attaching to a DOM could work. Please close this issue if you want to. :)

**Comment by OscarGodson** [comment]
There two different thing. The jQuery fragment is meant for jQuery
manipulation. You should handle you jQuery object separate from
EpicEditor. Also, just calling new EpicEditor() wont add it to the DOM
if that's what you're worried about. Wait until you're ready then call
load()
