### ISSUE TITLE
The 'this' object does not refer to the editor

### ISSUE THREAD

**Issue by davidshen84** [OscarGodson/EpicEditor#72]
```
var ee = new EpicEditor($('#editor).get(0));
ee.on('save', function() {
  alert(type of this);
});
```

The _this_ object referred to the HTML document that EE created in the IFrame. In this context, it should refer to the editor itself.

**Comment by OscarGodson** [comment]
You are totally right. I fixed this in our `0.1.0` branch.

`0.0.3`: https://github.com/OscarGodson/EpicEditor/blob/master/epiceditor.js#L761  
`0.1.0`: https://github.com/OscarGodson/EpicEditor/blob/0.1.0-build-refactor/src/editor.js#L930

Looks like you are doing some serious work on EE! Thats great. If so you should try checking out the `0.1.0-build-refactor` branch and let me know if you need help with it.
