### ISSUE TITLE
line break translated as double hard breaks

### ISSUE THREAD

**Issue by hmngwy** [OscarGodson/EpicEditor#75]
when I type in 

```
hello  
you
```

_please note there is two spaces after hello_
it's translated as

```
hello
<br>
<br>
you
```

where as per [daringfireball](http://daringfireball.net/projects/markdown/syntax#p) it should produce a single hard break.

> When you do want to insert a `<br />` break tag using Markdown, you end a line with two or more spaces, then type return.

**Comment by OscarGodson** [comment]
That actually matches GitHub flavored markdown, however, I agree that it seems wrong. Also, in the 0.1.0-build-refactor branch (the one that will become the 0.1.0 release) we use Marked and 2 spaces doesn't even work which is worse. I'm going to add this to the 0.1.0 milestone.

**Comment by OscarGodson** [comment]
@johnmdonahue - Since you said you'd have some time this weekend, do you wanna update @chjj Marked and see if this issue is fixed? Right now doing 2 spaces like above results in _no_ `<br>`s at all and instead literally adds 2 spaces which is wrong for GitHub flavored markdown and normal markdown.

**Comment by johnmdonahue** [comment]
@OscarGodson - Sure, I can take a look at this.

**Comment by chjj** [comment]
GFM line breaks were something I intentionally left out of marked because I think they are unnecessary (markdown already has a great mechanism for hard line breaks).

> we use Marked and 2 spaces doesn't even work which is worse

The two trailing spaces syntax should work fine:

``` bash
$ echo -e "hello  \nworld" | marked
<p>hello<br>world
</p>
```

**Comment by OscarGodson** [comment]
@chjj Strange... im seeing this: 

![md](https://img.skitch.com/20120420-kduk66jukfa3gwfrg8cqb4q69j.png)

However, it might also be because of my _set/_getText shim that i did to get Firefox to mimic `innerText` in all other browsers.

thanks a lot for responding, and I totally agree with you the GFM comment.

**Comment by chjj** [comment]
@OscarGodson, after looking at the _getText function, that may be it. If you can reproduce this problem with marked alone, let me know.

**Comment by OscarGodson** [comment]
@johnmdonahue fuuuuuuuck. It has to do with `JSON.parse()`. If you view our localStorage string you see:

``` json
{
  "files":{
    "example-1":"hello  \nworld"
  }
}
```

Notice the two spaces and the `\n`

However, if you do:

``` javascript
JSON.parse(localStorage['epiceditor']).files['example-1']
```

you get

```
hello  
world
```

There's two spaces, but no `\n`. It's stripping those out. Ugh.

**Comment by johnmdonahue** [comment]
Haven't really looked into it but could we maybe do a quick pre-processing before passing to the renderer:

``` javascript
JSON.parse(localStorage['epiceditor']).files['example-1'].replace(/\n/g, '\\n')
```

**Comment by OscarGodson** [comment]
@johnmdonahue Yeah, thats what im thinking we'll have to do in `exportFile` in the `html` (`marked()`) case. I sent this in tho: https://github.com/chjj/marked/issues/45

**Comment by OscarGodson** [comment]
Man. I'm really stumped on this. Doing:

```
marked('hello  \nworld');
```

Returns the right HTML:

``` html
<p>hello<br>world</p>
```

However, as we know the previewer (and `exportFile`) is saying the HTML is:

``` html
<p>Hello  
world</p>
```

Which is strange @chjj marked would even return a line break in the HTML at all in the middle of a string _and_ notice there's two spaces in that copy paste above after `Hello`.

So, to make sure I was giving the right thing to marked I did:

``` js
console.log(content.replace(/\n/g, '{n}').replace(/\s/g, '{s}'));
console.log(marked(content))
```

And it returns:

```
> Hello{s}{s}{n}world
> <p>Hello  
world</p>
```

Based on the first log thats _exactly_ the right thing. They're one line apart, nothing can change between them.

I'm totally out of things to test in EE. I'm going to look at Marked's source. One line above the marked call it's saying it's the exact right format and also marked is leaving a line break in the HTML.

@johnmdonahue - if you ever get time could you make sure I'm not crazy? :P

**Comment by chjj** [comment]
This happens out of the `exportFile` function? To test it, you should do: `console.log(content.replace(/\n/g, '{n}').replace(/ /g, '{s}'));` instead. Markdown requires two spaces, not any other kind of whitespace.

**Comment by OscarGodson** [comment]
@chjj thanks a lot! that worked. It says `{s} {n}`. Not sure what else that whitespace could be tho since I hit spacebar twice and one times it registers as a space the other not. I'll have to do some research.

**Comment by chjj** [comment]
Could be a tab, return carriage, vertical tab, form feed, etc. Very strange, but you should dump the bytes to see.

**Comment by OscarGodson** [comment]
@chjj Yep, thats what I was doing. Looks like for `hello  \nworld` it's returning:

`0048 0065 006c 006c 006f 0020 00a0 000a 0077 006f 0072 006c 0064`

Or, a space then a "no-break space" (`&nbsp;`). I guess I'll convert: `\u00a0` to `\u0020`. Talk about hacky...

**Comment by chjj** [comment]
Cool. By the way, I recommend upgrading marked to v0.2.5, which fixes some inaccuracies with how list items interact with  `<hr>`.

**Comment by OscarGodson** [comment]
@chjj Done! thanks @johnmdonahue
