### ISSUE TITLE
Clean up the options list

### ISSUE THREAD

**Issue by OscarGodson** [OscarGodson/EpicEditor#77]
This is ugly:

![ugly](https://img.skitch.com/20120421-jyfxd7efkirqg4drbcr4rs9fwp.png)

**Comment by OscarGodson** [comment]
I'd consider it a slight improvement ;)

![new options](https://img.skitch.com/20120511-b9gkhjs9mpbm32f8ntutyrhn33.png)

In the same commit I did this to the events too.

cc: @sebnitu - you think this looks OK?

**Comment by sebnitu** [comment]
I love it man, that looks awesome :D (huge improvement)
