### ISSUE TITLE
Make a helper method for getting a file's localStorage object

### ISSUE THREAD

**Issue by OscarGodson** [OscarGodson/EpicEditor#85]
Tired of writing:

``` javascript
JSON.parse(localStorage[self.settings.localStorageName]).file[self.settings.file.name];
```

Would rather write:

``` javascript
// Returns `JSON.parse(localStorage[self.settings.localStorageName])`
self.files();

//Returns `JSON.parse(localStorage[self.settings.localStorageName]).file[NAME]`
self.files(self.settings.file.name);
```

This should also be a public API method so devs can get files out without affecting the GUI.

**Comment by OscarGodson** [comment]
@johnmdonahue This is done and working, just have to write tests, but the naming part is the hardest. I went with `fileList([name])`. How do you feel about that? I wanted to do `file` or `files` but that felt like you should be able to do more with it like import and export. I was thinking about the Node and thought of `fs`, but too vague. Any other ideas?

**Comment by OscarGodson** [comment]
Think it should maybe be `getFiles()` to match `getElements()` and the fact we have a sort of `actionNoun` thing going too with `importFile`, `exportFile`, `getElements`, etc.

**Comment by johnmdonahue** [comment]
Late to the party but +1 on `getFiles()`
