### ISSUE TITLE
Anchors (not links) shouldn't open in a new tab

### ISSUE THREAD

**Issue by OscarGodson** [OscarGodson/EpicEditor#96]
If you copy and paste our README then click on the `on()` link in the Events section it'll open a new page. It's just a `#link` anchor so it shouldn't do this.

**Comment by johnmdonahue** [comment]
Just to clarify: This is an issue on EE? So copying and pasting anchor links into an EE instance makes the links open new tabs, correct?

If so, it looks like it's an issue with the target attr. If it seems like a big enough issue maybe could catch clicks and force the target to `_self` if the link appears to be internal (i.e. begins with "#*").

``` html
<a href="#onevent-handler" target="_self">
```

As a side note when looking at this I ran into an interesting bug. If you click a link that opens a new tab while in full screen mode, it obviously kicks you out of fullscreen. If you then try to switch back to edit mode, any key press will return you to preview mode until you refresh the EE instance. Let me know if you can reproduce. (Chrome)

**Comment by OscarGodson** [comment]
Yes. Ticket #76 fixed external links. I did a easy fix by adding a base tag:

Commit:
https://github.com/OscarGodson/EpicEditor/commit/989ffa11fffbec166a7258aa389a35673d087cd5

Current src:
https://github.com/OscarGodson/EpicEditor/blob/0.1.0-build-refactor/src/editor.js#L417-L420

I did this because the alternative would be to inject a script that traverses all the `<a>`s and that seemed icky and exactly what the `<base>` tag is for. I think we should inject some script that looks for `a[href^="#"]` and adds `target="_self"` to them.

**Comment by OscarGodson** [comment]
Also @johnmdonahue I can't repro what you explained, however I might be taking the wrong steps:
1. Open the EE docs with our EE README as the content
2. Click full screen
3. Click the github link
4. After it loads github, go back to my EE tab
5. I press alt+p and it previews
6. I press alt+o and it goes back to edit

**Comment by johnmdonahue** [comment]
Hmm very strange. It happens on my end every time. Here is what I am doing in Chrome(18.0.1025.168):
1. Copy https://raw.github.com/OscarGodson/EpicEditor/0.1.0-build-refactor/README.md into a local 0.1.0-build-refactor EE `index.html` editor.
2. Click on fullscreen.
3. Click on `on()` anchor in events section (Or any other link that opens a new tab)
4. Go back to EE tab
5. If not already in edit mode, go to edit mode by clicking edit/preview toggle or shortcut
6. Start typing anything (e.g. space bar)
7. Switches back to preview mode

Same behavior occurs in Safari except opening the new tab does not close fullscreen. Also it doesn't seem to matter if shortcuts are used or UI buttons.

**Comment by OscarGodson** [comment]
Awh, yep. Shit, actually even just closing full screen with esc does this. This is most likely from:

https://github.com/OscarGodson/EpicEditor/blob/0.1.0-build-refactor/src/editor.js#L568

We need to remove that handler when fullscreen is closed is all (probably). I'd make a new ticket tho. This affects IE9, FF, and Chrome. And make it important ;)

**Comment by OscarGodson** [comment]
@johnmdonahue added what you reported to ticket #97 and fixed it.

**Comment by johnmdonahue** [comment]
@OscarGodson So this is closed right?

**Comment by OscarGodson** [comment]
No. The other one you reported in this ticket was.

On May 13, 2012, at 8:42 PM, John Donahue
reply@reply.github.com
wrote:

**Comment by johnmdonahue** [comment]
Whoops. :)

**Comment by OscarGodson** [comment]
This isn't working on Firefox. GOD.

**Comment by OscarGodson** [comment]
Going to reclose this since this is a long outstanding Firefox bug. Theres no decent way to hack it either. The hack would be gnarly and only for Firefox so instead [I reported it](https://bugzilla.mozilla.org/show_bug.cgi?id=824304) and they seem to be looking at it now, hopefully.
