### ISSUE TITLE
Clicking external link while in full screen breaks preview/edit views

### ISSUE THREAD

**Issue by OscarGodson** [OscarGodson/EpicEditor#97]
This is a pretty important one @johnmdonahue found and reported in #96.
1. Open EE
2. In an empty doc type something
3. Open full screen
4. Close full screen (i.e. press <kbd>esc</kbd>)
5. Now, go back to the editor and start typing anything

You'll notice preview opens and you can't get it to go away.

This almost positively has to do with this line:

https://github.com/OscarGodson/EpicEditor/blob/0.1.0-build-refactor/src/editor.js#L568

We need to remove the listener on fullscreen exit.

**Comment by johnmdonahue** [comment]
Squashing bugs like a boss. :punch:

**Comment by OscarGodson** [comment]
@johnmdonahue indeed! Down to 10 as of now.
