### ISSUE TITLE
Script injection

### ISSUE THREAD

**Issue by OscarGodson** [OscarGodson/EpicEditor#99]
So, I'm not sure why someone would do this to themselves but if they did:

``` md
<iframe/onload=top.document.write(1)>
```

or like

```
<img src=x onerror=alert(1)>
```

Reported by: @superevr on twitter 

Esp. the first. If you do it you can't ever view the page again without manually changing the content via the API or through localStorage.

Because this is more annoying than anything and you should be handling script injections when importing data into your DB anyways, I'm gonna make this a 1.0 ticket.

**Comment by OscarGodson** [comment]
Maybe this isn't our issue at all. I mean, what are the chances of a non tech savvy person writing something like the above? Plus, what if you wanted to do something like JSBin with EpicEditor? Should we close this?

cc: @johnmdonahue @dadambickford

**Comment by johnmdonahue** [comment]
Agreed. I don't think this is really an EE issue. If people run into specific problems with this maybe we could reevaluate then.
